// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: storage/v1/rom.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RomMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: `json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *RomMetadata) Reset() {
	*x = RomMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RomMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomMetadata) ProtoMessage() {}

func (x *RomMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomMetadata.ProtoReflect.Descriptor instead.
func (*RomMetadata) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{0}
}

func (x *RomMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RomMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type RomGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *RomGetRequest) Reset() {
	*x = RomGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RomGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomGetRequest) ProtoMessage() {}

func (x *RomGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomGetRequest.ProtoReflect.Descriptor instead.
func (*RomGetRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{1}
}

func (x *RomGetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomGetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type RomDownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *RomDownloadRequest) Reset() {
	*x = RomDownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RomDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDownloadRequest) ProtoMessage() {}

func (x *RomDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDownloadRequest.ProtoReflect.Descriptor instead.
func (*RomDownloadRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{2}
}

func (x *RomDownloadRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomDownloadRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RomListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *RomListRequest) Reset() {
	*x = RomListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomListRequest) ProtoMessage() {}

func (x *RomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomListRequest.ProtoReflect.Descriptor instead.
func (*RomListRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{4}
}

func (x *RomListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type RomListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roms []*RomMetadata `protobuf:"bytes,1,rep,name=roms,proto3" json:"roms,omitempty"`
}

func (x *RomListResponse) Reset() {
	*x = RomListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomListResponse) ProtoMessage() {}

func (x *RomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomListResponse.ProtoReflect.Descriptor instead.
func (*RomListResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{5}
}

func (x *RomListResponse) GetRoms() []*RomMetadata {
	if x != nil {
		return x.Roms
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: `json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{6}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type RomUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RequestData:
	//
	//	*RomUploadRequest_FileInfo
	//	*RomUploadRequest_ChunkData
	RequestData isRomUploadRequest_RequestData `protobuf_oneof:"request_data"`
}

func (x *RomUploadRequest) Reset() {
	*x = RomUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RomUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadRequest) ProtoMessage() {}

func (x *RomUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadRequest.ProtoReflect.Descriptor instead.
func (*RomUploadRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{7}
}

func (m *RomUploadRequest) GetRequestData() isRomUploadRequest_RequestData {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (x *RomUploadRequest) GetFileInfo() *FileInfo {
	if x, ok := x.GetRequestData().(*RomUploadRequest_FileInfo); ok {
		return x.FileInfo
	}
	return nil
}

func (x *RomUploadRequest) GetChunkData() []byte {
	if x, ok := x.GetRequestData().(*RomUploadRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isRomUploadRequest_RequestData interface {
	isRomUploadRequest_RequestData()
}

type RomUploadRequest_FileInfo struct {
	// @gotags: `json:"fileInfo,omitempty" bson:"fileInfo,omitempty"`
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof"`
}

type RomUploadRequest_ChunkData struct {
	// @gotags: `json:"chunkData,omitempty" bson:"chunkData,omitempty"`
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*RomUploadRequest_FileInfo) isRomUploadRequest_RequestData() {}

func (*RomUploadRequest_ChunkData) isRomUploadRequest_RequestData() {}

type RomUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: `json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	MimeType string `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
}

func (x *RomUploadResponse) Reset() {
	*x = RomUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storage_v1_rom_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RomUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadResponse) ProtoMessage() {}

func (x *RomUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_rom_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadResponse.ProtoReflect.Descriptor instead.
func (*RomUploadResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_rom_proto_rawDescGZIP(), []int{8}
}

func (x *RomUploadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomUploadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RomUploadResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_storage_v1_rom_proto protoreflect.FileDescriptor

var file_storage_v1_rom_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x22, 0x4e, 0x0a, 0x0b, 0x52, 0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x4d, 0x0a, 0x0d, 0x52, 0x6f, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x52, 0x0a, 0x12, 0x52, 0x6f, 0x6d, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x0e, 0x52, 0x6f, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x0f, 0x52, 0x6f,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x04, 0x72, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6d, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x72, 0x6f, 0x6d, 0x73, 0x22, 0x3b, 0x0a, 0x08, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69,
	0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x78, 0x0a, 0x10, 0x52, 0x6f, 0x6d, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1f, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x0e, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x54, 0x0a, 0x11, 0x52, 0x6f, 0x6d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69,
	0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x79, 0x75, 0x75, 0x53, 0x61, 0x78, 0x65, 0x6e, 0x61,
	0x2f, 0x6d, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_storage_v1_rom_proto_rawDescOnce sync.Once
	file_storage_v1_rom_proto_rawDescData = file_storage_v1_rom_proto_rawDesc
)

func file_storage_v1_rom_proto_rawDescGZIP() []byte {
	file_storage_v1_rom_proto_rawDescOnce.Do(func() {
		file_storage_v1_rom_proto_rawDescData = protoimpl.X.CompressGZIP(file_storage_v1_rom_proto_rawDescData)
	})
	return file_storage_v1_rom_proto_rawDescData
}

var file_storage_v1_rom_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_storage_v1_rom_proto_goTypes = []any{
	(*RomMetadata)(nil),        // 0: storage.v1.RomMetadata
	(*RomGetRequest)(nil),      // 1: storage.v1.RomGetRequest
	(*RomDownloadRequest)(nil), // 2: storage.v1.RomDownloadRequest
	(*FileChunk)(nil),          // 3: storage.v1.FileChunk
	(*RomListRequest)(nil),     // 4: storage.v1.RomListRequest
	(*RomListResponse)(nil),    // 5: storage.v1.RomListResponse
	(*FileInfo)(nil),           // 6: storage.v1.FileInfo
	(*RomUploadRequest)(nil),   // 7: storage.v1.RomUploadRequest
	(*RomUploadResponse)(nil),  // 8: storage.v1.RomUploadResponse
}
var file_storage_v1_rom_proto_depIdxs = []int32{
	0, // 0: storage.v1.RomListResponse.roms:type_name -> storage.v1.RomMetadata
	6, // 1: storage.v1.RomUploadRequest.file_info:type_name -> storage.v1.FileInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storage_v1_rom_proto_init() }
func file_storage_v1_rom_proto_init() {
	if File_storage_v1_rom_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storage_v1_rom_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RomMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RomGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RomDownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FileChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*RomListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RomListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RomUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storage_v1_rom_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*RomUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_storage_v1_rom_proto_msgTypes[1].OneofWrappers = []any{}
	file_storage_v1_rom_proto_msgTypes[2].OneofWrappers = []any{}
	file_storage_v1_rom_proto_msgTypes[4].OneofWrappers = []any{}
	file_storage_v1_rom_proto_msgTypes[7].OneofWrappers = []any{
		(*RomUploadRequest_FileInfo)(nil),
		(*RomUploadRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storage_v1_rom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_v1_rom_proto_goTypes,
		DependencyIndexes: file_storage_v1_rom_proto_depIdxs,
		MessageInfos:      file_storage_v1_rom_proto_msgTypes,
	}.Build()
	File_storage_v1_rom_proto = out.File
	file_storage_v1_rom_proto_rawDesc = nil
	file_storage_v1_rom_proto_goTypes = nil
	file_storage_v1_rom_proto_depIdxs = nil
}
