// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: common/v1/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommonListRequest represents the standardized request parameters for paginated listings across all services.
type CommonListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of items to return (default 20, max 100)
	// @gotags: `form:"limit" json:"limit,omitempty" bson:"limit,omitempty"`
	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty" form:"limit" bson:"limit,omitempty"`
	// Number of items to skip for pagination (default 0)
	// @gotags: `form:"offset" json:"offset,omitempty" bson:"offset,omitempty"`
	Offset *int32 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty" form:"offset" bson:"offset,omitempty"`
	// Search keyword across text fields
	// @gotags: `form:"keyword" json:"keyword,omitempty" bson:"keyword,omitempty"`
	Keyword *string `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty" form:"keyword" bson:"keyword,omitempty"`
	// Field name to sort by (e.g. title, createdAt)
	// @gotags: `form:"sortby" json:"sortby,omitempty" bson:"sortby,omitempty"`
	Sortby *string `protobuf:"bytes,4,opt,name=sortby,proto3,oneof" json:"sortby,omitempty" form:"sortby" bson:"sortby,omitempty"`
	// Sort direction order (asc or desc, default desc)
	// @gotags: `form:"sortOrder" json:"sortOrder,omitempty" bson:"sortOrder,omitempty"`
	SortOrder     *string `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sortOrder,omitempty" form:"sortOrder" bson:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonListRequest) Reset() {
	*x = CommonListRequest{}
	mi := &file_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonListRequest) ProtoMessage() {}

func (x *CommonListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonListRequest.ProtoReflect.Descriptor instead.
func (*CommonListRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonListRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *CommonListRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *CommonListRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *CommonListRequest) GetSortby() string {
	if x != nil && x.Sortby != nil {
		return *x.Sortby
	}
	return ""
}

func (x *CommonListRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

// CommonListResponse represents standardized pagination metadata across all services.
type CommonListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total count of matching items
	// @gotags: `json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	TotalCount int64 `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	// Page size limit applied
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset applied
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// Total calculated number of pages
	// @gotags: `json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	TotalPages    int32 `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonListResponse) Reset() {
	*x = CommonListResponse{}
	mi := &file_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonListResponse) ProtoMessage() {}

func (x *CommonListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonListResponse.ProtoReflect.Descriptor instead.
func (*CommonListResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *CommonListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CommonListResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CommonListResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CommonListResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// FileMetadata describes a storage file record returned from the S3-Free database.
type FileMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB internal record identifier (_id)
	// @gotags: `json:"mongoId,omitempty" bson:"_id,omitempty"`
	MongoId string `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongoId,omitempty" bson:"_id,omitempty"`
	// UUID file identifier in storage database
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site string `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	// Bucket name containing this file
	// @gotags: `json:"bucketId,omitempty" bson:"bucketId,omitempty"`
	BucketId string `protobuf:"bytes,4,opt,name=bucket_id,json=bucketId,proto3" json:"bucketId,omitempty" bson:"bucketId,omitempty"`
	// Directory path within the bucket
	Directory string `protobuf:"bytes,5,opt,name=directory,proto3" json:"directory,omitempty"`
	// File base name
	Name string `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// File extension without leading dot
	// @gotags: `json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	FileExtension string `protobuf:"bytes,7,opt,name=file_extension,json=fileExtension,proto3" json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	// Full storage path (directory/name)
	// @gotags: `json:"fullPath,omitempty" bson:"fullPath,omitempty"`
	FullPath string `protobuf:"bytes,8,opt,name=full_path,json=fullPath,proto3" json:"fullPath,omitempty" bson:"fullPath,omitempty"`
	// MIME content type
	// @gotags: `json:"contentType,omitempty" bson:"contentType,omitempty"`
	ContentType string `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"contentType,omitempty" bson:"contentType,omitempty"`
	// File size in bytes
	// @gotags: `json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	SizeBytes int64 `protobuf:"varint,10,opt,name=size_bytes,json=sizeBytes,proto3" json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	// ETag / checksum of the file
	Etag string `protobuf:"bytes,11,opt,name=etag,proto3" json:"etag,omitempty"`
	// ISO-8601 creation timestamp
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt     string `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *FileMetadata) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *FileMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileMetadata) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *FileMetadata) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *FileMetadata) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *FileMetadata) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileMetadata) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *FileMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// FileChunk represents binary chunk data for file streaming.
type FileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Binary chunk data
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_common_v1_common_proto protoreflect.FileDescriptor

const file_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/common.proto\x12\tcommon.v1\"\xe6\x01\n" +
	"\x11CommonListRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tH\x02R\akeyword\x88\x01\x01\x12\x1b\n" +
	"\x06sortby\x18\x04 \x01(\tH\x03R\x06sortby\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tH\x04R\tsortOrder\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\n" +
	"\n" +
	"\b_keywordB\t\n" +
	"\a_sortbyB\r\n" +
	"\v_sort_order\"\x84\x01\n" +
	"\x12CommonListResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xd5\x02\n" +
	"\fFileMetadata\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x03 \x01(\tR\x04site\x12\x1b\n" +
	"\tbucket_id\x18\x04 \x01(\tR\bbucketId\x12\x1c\n" +
	"\tdirectory\x18\x05 \x01(\tR\tdirectory\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12%\n" +
	"\x0efile_extension\x18\a \x01(\tR\rfileExtension\x12\x1b\n" +
	"\tfull_path\x18\b \x01(\tR\bfullPath\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\n" +
	" \x01(\x03R\tsizeBytes\x12\x12\n" +
	"\x04etag\x18\v \x01(\tR\x04etag\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataB2Z0github.com/AyuuSaxena/protos-go/common/v1;commonb\x06proto3"

var (
	file_common_v1_common_proto_rawDescOnce sync.Once
	file_common_v1_common_proto_rawDescData []byte
)

func file_common_v1_common_proto_rawDescGZIP() []byte {
	file_common_v1_common_proto_rawDescOnce.Do(func() {
		file_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)))
	})
	return file_common_v1_common_proto_rawDescData
}

var file_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_v1_common_proto_goTypes = []any{
	(*CommonListRequest)(nil),  // 0: common.v1.CommonListRequest
	(*CommonListResponse)(nil), // 1: common.v1.CommonListResponse
	(*FileMetadata)(nil),       // 2: common.v1.FileMetadata
	(*FileChunk)(nil),          // 3: common.v1.FileChunk
}
var file_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_common_proto_init() }
func file_common_v1_common_proto_init() {
	if File_common_v1_common_proto != nil {
		return
	}
	file_common_v1_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_common_proto_rawDesc), len(file_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_common_proto_goTypes,
		DependencyIndexes: file_common_v1_common_proto_depIdxs,
		MessageInfos:      file_common_v1_common_proto_msgTypes,
	}.Build()
	File_common_v1_common_proto = out.File
	file_common_v1_common_proto_goTypes = nil
	file_common_v1_common_proto_depIdxs = nil
}
