// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: identity/v1/identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Site  string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: `json:"googleId,omitempty" bson:"googleId,omitempty"`
	GoogleId string `protobuf:"bytes,3,opt,name=google_id,json=googleId,proto3" json:"googleId,omitempty" bson:"googleId,omitempty"`
	// @gotags: `json:"profileUrl,omitempty" bson:"profileUrl,omitempty"`
	ProfileUrl string `protobuf:"bytes,4,opt,name=profile_url,json=profileUrl,proto3" json:"profileUrl,omitempty" bson:"profileUrl,omitempty"`
	Username   string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	// @gotags: `json:"firstName,omitempty" bson:"firstName,omitempty"`
	FirstName string `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"firstName,omitempty" bson:"firstName,omitempty"`
	// @gotags: `json:"lastName,omitempty" bson:"lastName,omitempty"`
	LastName string `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"lastName,omitempty" bson:"lastName,omitempty"`
	// @gotags: `json:"fullName,omitempty" bson:"fullName,omitempty"`
	FullName string `protobuf:"bytes,8,opt,name=full_name,json=fullName,proto3" json:"fullName,omitempty" bson:"fullName,omitempty"`
	// @gotags: `json:"phoneNumber,omitempty" bson:"phoneNumber,omitempty"`
	PhoneNumber *string `protobuf:"bytes,9,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phoneNumber,omitempty" bson:"phoneNumber,omitempty"`
	Email       string  `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Password    string  `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	Postalcode  *string `protobuf:"bytes,12,opt,name=postalcode,proto3,oneof" json:"postalcode,omitempty"`
	City        *string `protobuf:"bytes,13,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State       *string `protobuf:"bytes,14,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Country     *string `protobuf:"bytes,15,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Timezone    *string `protobuf:"bytes,16,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	// @gotags: `json:"isVerifi6ed,omitempty" bson:"isVerified,omitempty"`
	IsVerified bool `protobuf:"varint,30,opt,name=is_verified,json=isVerified,proto3" json:"isVerifi6ed,omitempty" bson:"isVerified,omitempty"`
	// @gotags: `json:"isActive,omitempty" bson:"isActive,omitempty"`
	IsActive bool `protobuf:"varint,31,opt,name=is_active,json=isActive,proto3" json:"isActive,omitempty" bson:"isActive,omitempty"`
	// @gotags: `json:"addedDate,omitempty" bson:"addedDate,omitempty"`
	AddedAt int64 `protobuf:"varint,32,opt,name=added_at,json=addedAt,proto3" json:"addedDate,omitempty" bson:"addedDate,omitempty"`
	// @gotags: `json:"updatedDate,omitempty" bson:"updatedDate,omitempty"`
	UpdatedAt     int64 `protobuf:"varint,33,opt,name=updated_at,json=updatedAt,proto3" json:"updatedDate,omitempty" bson:"updatedDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetGoogleId() string {
	if x != nil {
		return x.GoogleId
	}
	return ""
}

func (x *Identity) GetProfileUrl() string {
	if x != nil {
		return x.ProfileUrl
	}
	return ""
}

func (x *Identity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Identity) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Identity) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Identity) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Identity) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Identity) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Identity) GetPostalcode() string {
	if x != nil && x.Postalcode != nil {
		return *x.Postalcode
	}
	return ""
}

func (x *Identity) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Identity) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Identity) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Identity) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *Identity) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *Identity) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Identity) GetAddedAt() int64 {
	if x != nil {
		return x.AddedAt
	}
	return 0
}

func (x *Identity) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type IdentityCreateAccountRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Site     string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id       string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Username *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// @gotags: `json:"fullName,omitempty" bson:"fullName,omitempty"`
	FullName string `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"fullName,omitempty" bson:"fullName,omitempty"`
	// @gotags: `json:"profileUrl,omitempty" bson:"profileUrl,omitempty"`
	ProfileUrl    *string `protobuf:"bytes,5,opt,name=profile_url,json=profileUrl,proto3,oneof" json:"profileUrl,omitempty" bson:"profileUrl,omitempty"`
	PhoneNumber   *string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phone_number,omitempty"`
	Email         string  `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Password      string  `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Postalcode    *string `protobuf:"bytes,21,opt,name=postalcode,proto3,oneof" json:"postalcode,omitempty"`
	City          *string `protobuf:"bytes,22,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string `protobuf:"bytes,23,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Country       *string `protobuf:"bytes,24,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Timezone      *string `protobuf:"bytes,25,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityCreateAccountRequest) Reset() {
	*x = IdentityCreateAccountRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityCreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityCreateAccountRequest) ProtoMessage() {}

func (x *IdentityCreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityCreateAccountRequest.ProtoReflect.Descriptor instead.
func (*IdentityCreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityCreateAccountRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetProfileUrl() string {
	if x != nil && x.ProfileUrl != nil {
		return *x.ProfileUrl
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetPostalcode() string {
	if x != nil && x.Postalcode != nil {
		return *x.Postalcode
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *IdentityCreateAccountRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

type IdentityCreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityCreateAccountResponse) Reset() {
	*x = IdentityCreateAccountResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityCreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityCreateAccountResponse) ProtoMessage() {}

func (x *IdentityCreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityCreateAccountResponse.ProtoReflect.Descriptor instead.
func (*IdentityCreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *IdentityCreateAccountResponse) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityCreateAccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IdentityOtpVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Otp           string                 `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityOtpVerifyRequest) Reset() {
	*x = IdentityOtpVerifyRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityOtpVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityOtpVerifyRequest) ProtoMessage() {}

func (x *IdentityOtpVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityOtpVerifyRequest.ProtoReflect.Descriptor instead.
func (*IdentityOtpVerifyRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityOtpVerifyRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityOtpVerifyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityOtpVerifyRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type IdentityGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityGetRequest) Reset() {
	*x = IdentityGetRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityGetRequest) ProtoMessage() {}

func (x *IdentityGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityGetRequest.ProtoReflect.Descriptor instead.
func (*IdentityGetRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityGetRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityGetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IdentityUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Site  string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: `json:"googleId,omitempty" bson:"googleId,omitempty"`
	GoogleId string `protobuf:"bytes,3,opt,name=google_id,json=googleId,proto3" json:"googleId,omitempty" bson:"googleId,omitempty"`
	// @gotags: `json:"profileUrl,omitempty" bson:"profileUrl,omitempty"`
	ProfileUrl *string `protobuf:"bytes,4,opt,name=profile_url,json=profileUrl,proto3,oneof" json:"profileUrl,omitempty" bson:"profileUrl,omitempty"`
	Username   *string `protobuf:"bytes,5,opt,name=username,proto3,oneof" json:"username,omitempty"`
	// @gotags: `json:"fullName,omitempty" bson:"fullName,omitempty"`
	FullName *string `protobuf:"bytes,6,opt,name=full_name,json=fullName,proto3,oneof" json:"fullName,omitempty" bson:"fullName,omitempty"`
	// @gotags: `json:"phoneNumber,omitempty" bson:"phoneNumber,omitempty"`
	PhoneNumber   *string `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phoneNumber,omitempty" bson:"phoneNumber,omitempty"`
	Email         *string `protobuf:"bytes,8,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Password      *string `protobuf:"bytes,9,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Postalcode    *string `protobuf:"bytes,21,opt,name=postalcode,proto3,oneof" json:"postalcode,omitempty"`
	City          *string `protobuf:"bytes,22,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string `protobuf:"bytes,23,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Country       *string `protobuf:"bytes,24,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Timezone      *string `protobuf:"bytes,25,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityUpdateRequest) Reset() {
	*x = IdentityUpdateRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityUpdateRequest) ProtoMessage() {}

func (x *IdentityUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityUpdateRequest.ProtoReflect.Descriptor instead.
func (*IdentityUpdateRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *IdentityUpdateRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityUpdateRequest) GetGoogleId() string {
	if x != nil {
		return x.GoogleId
	}
	return ""
}

func (x *IdentityUpdateRequest) GetProfileUrl() string {
	if x != nil && x.ProfileUrl != nil {
		return *x.ProfileUrl
	}
	return ""
}

func (x *IdentityUpdateRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *IdentityUpdateRequest) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *IdentityUpdateRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *IdentityUpdateRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *IdentityUpdateRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *IdentityUpdateRequest) GetPostalcode() string {
	if x != nil && x.Postalcode != nil {
		return *x.Postalcode
	}
	return ""
}

func (x *IdentityUpdateRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *IdentityUpdateRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *IdentityUpdateRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *IdentityUpdateRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

type IdentityAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Otp           *int32                 `protobuf:"varint,4,opt,name=otp,proto3,oneof" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityAuthRequest) Reset() {
	*x = IdentityAuthRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityAuthRequest) ProtoMessage() {}

func (x *IdentityAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityAuthRequest.ProtoReflect.Descriptor instead.
func (*IdentityAuthRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityAuthRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IdentityAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *IdentityAuthRequest) GetOtp() int32 {
	if x != nil && x.Otp != nil {
		return *x.Otp
	}
	return 0
}

type IdentityAuthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: `json:"authorizationToken,omitempty" bson:"authorizationToken,omitempty"`
	AuthorizationToken string `protobuf:"bytes,1,opt,name=authorization_token,json=authorizationToken,proto3" json:"authorizationToken,omitempty" bson:"authorizationToken,omitempty"`
	// @gotags: `json:"refreshToken,omitempty" bson:"refreshToken,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken,omitempty" bson:"refreshToken,omitempty"`
	// @gotags: `json:"userId,omitempty" bson:"userId,omitempty"`
	UserId        string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"userId,omitempty" bson:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityAuthResponse) Reset() {
	*x = IdentityAuthResponse{}
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityAuthResponse) ProtoMessage() {}

func (x *IdentityAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityAuthResponse.ProtoReflect.Descriptor instead.
func (*IdentityAuthResponse) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *IdentityAuthResponse) GetAuthorizationToken() string {
	if x != nil {
		return x.AuthorizationToken
	}
	return ""
}

func (x *IdentityAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *IdentityAuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IdentityRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRefreshTokenRequest) Reset() {
	*x = IdentityRefreshTokenRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRefreshTokenRequest) ProtoMessage() {}

func (x *IdentityRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*IdentityRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *IdentityRefreshTokenRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityRefreshTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityRefreshTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IdentityOtpValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Otp           string                 `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityOtpValidateRequest) Reset() {
	*x = IdentityOtpValidateRequest{}
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityOtpValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityOtpValidateRequest) ProtoMessage() {}

func (x *IdentityOtpValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityOtpValidateRequest.ProtoReflect.Descriptor instead.
func (*IdentityOtpValidateRequest) Descriptor() ([]byte, []int) {
	return file_identity_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *IdentityOtpValidateRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityOtpValidateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityOtpValidateRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

var File_identity_v1_identity_proto protoreflect.FileDescriptor

const file_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x1aidentity/v1/identity.proto\x12\videntity.v1\"\x98\x05\n" +
	"\bIdentity\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tgoogle_id\x18\x03 \x01(\tR\bgoogleId\x12\x1f\n" +
	"\vprofile_url\x18\x04 \x01(\tR\n" +
	"profileUrl\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x1b\n" +
	"\tfull_name\x18\b \x01(\tR\bfullName\x12&\n" +
	"\fphone_number\x18\t \x01(\tH\x00R\vphoneNumber\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\v \x01(\tR\bpassword\x12#\n" +
	"\n" +
	"postalcode\x18\f \x01(\tH\x01R\n" +
	"postalcode\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\r \x01(\tH\x02R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x0e \x01(\tH\x03R\x05state\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x0f \x01(\tH\x04R\acountry\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\x10 \x01(\tH\x05R\btimezone\x88\x01\x01\x12\x1f\n" +
	"\vis_verified\x18\x1e \x01(\bR\n" +
	"isVerified\x12\x1b\n" +
	"\tis_active\x18\x1f \x01(\bR\bisActive\x12\x19\n" +
	"\badded_at\x18  \x01(\x03R\aaddedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18! \x01(\x03R\tupdatedAtB\x0f\n" +
	"\r_phone_numberB\r\n" +
	"\v_postalcodeB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_timezone\"\x82\x04\n" +
	"\x1cIdentityCreateAccountRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12$\n" +
	"\vprofile_url\x18\x05 \x01(\tH\x01R\n" +
	"profileUrl\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\x06 \x01(\tH\x02R\vphoneNumber\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12#\n" +
	"\n" +
	"postalcode\x18\x15 \x01(\tH\x03R\n" +
	"postalcode\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x16 \x01(\tH\x04R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x17 \x01(\tH\x05R\x05state\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x18 \x01(\tH\x06R\acountry\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\x19 \x01(\tH\aR\btimezone\x88\x01\x01B\v\n" +
	"\t_usernameB\x0e\n" +
	"\f_profile_urlB\x0f\n" +
	"\r_phone_numberB\r\n" +
	"\v_postalcodeB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_timezone\"C\n" +
	"\x1dIdentityCreateAccountResponse\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"P\n" +
	"\x18IdentityOtpVerifyRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\tR\x03otp\"N\n" +
	"\x12IdentityGetRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xcc\x04\n" +
	"\x15IdentityUpdateRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tgoogle_id\x18\x03 \x01(\tR\bgoogleId\x12$\n" +
	"\vprofile_url\x18\x04 \x01(\tH\x00R\n" +
	"profileUrl\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x05 \x01(\tH\x01R\busername\x88\x01\x01\x12 \n" +
	"\tfull_name\x18\x06 \x01(\tH\x02R\bfullName\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\a \x01(\tH\x03R\vphoneNumber\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\b \x01(\tH\x04R\x05email\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\t \x01(\tH\x05R\bpassword\x88\x01\x01\x12#\n" +
	"\n" +
	"postalcode\x18\x15 \x01(\tH\x06R\n" +
	"postalcode\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x16 \x01(\tH\aR\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x17 \x01(\tH\bR\x05state\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x18 \x01(\tH\tR\acountry\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\x19 \x01(\tH\n" +
	"R\btimezone\x88\x01\x01B\x0e\n" +
	"\f_profile_urlB\v\n" +
	"\t_usernameB\f\n" +
	"\n" +
	"_full_nameB\x0f\n" +
	"\r_phone_numberB\b\n" +
	"\x06_emailB\v\n" +
	"\t_passwordB\r\n" +
	"\v_postalcodeB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_timezone\"z\n" +
	"\x13IdentityAuthRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x15\n" +
	"\x03otp\x18\x04 \x01(\x05H\x00R\x03otp\x88\x01\x01B\x06\n" +
	"\x04_otp\"\x85\x01\n" +
	"\x14IdentityAuthResponse\x12/\n" +
	"\x13authorization_token\x18\x01 \x01(\tR\x12authorizationToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"W\n" +
	"\x1bIdentityRefreshTokenRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"R\n" +
	"\x1aIdentityOtpValidateRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\tR\x03otpB6Z4github.com/AyuuSaxena/protos-go/identity/v1;identityb\x06proto3"

var (
	file_identity_v1_identity_proto_rawDescOnce sync.Once
	file_identity_v1_identity_proto_rawDescData []byte
)

func file_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)))
	})
	return file_identity_v1_identity_proto_rawDescData
}

var file_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_identity_v1_identity_proto_goTypes = []any{
	(*Identity)(nil),                      // 0: identity.v1.Identity
	(*IdentityCreateAccountRequest)(nil),  // 1: identity.v1.IdentityCreateAccountRequest
	(*IdentityCreateAccountResponse)(nil), // 2: identity.v1.IdentityCreateAccountResponse
	(*IdentityOtpVerifyRequest)(nil),      // 3: identity.v1.IdentityOtpVerifyRequest
	(*IdentityGetRequest)(nil),            // 4: identity.v1.IdentityGetRequest
	(*IdentityUpdateRequest)(nil),         // 5: identity.v1.IdentityUpdateRequest
	(*IdentityAuthRequest)(nil),           // 6: identity.v1.IdentityAuthRequest
	(*IdentityAuthResponse)(nil),          // 7: identity.v1.IdentityAuthResponse
	(*IdentityRefreshTokenRequest)(nil),   // 8: identity.v1.IdentityRefreshTokenRequest
	(*IdentityOtpValidateRequest)(nil),    // 9: identity.v1.IdentityOtpValidateRequest
}
var file_identity_v1_identity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_v1_identity_proto_init() }
func file_identity_v1_identity_proto_init() {
	if File_identity_v1_identity_proto != nil {
		return
	}
	file_identity_v1_identity_proto_msgTypes[0].OneofWrappers = []any{}
	file_identity_v1_identity_proto_msgTypes[1].OneofWrappers = []any{}
	file_identity_v1_identity_proto_msgTypes[5].OneofWrappers = []any{}
	file_identity_v1_identity_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_identity_proto_rawDesc), len(file_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_identity_v1_identity_proto = out.File
	file_identity_v1_identity_proto_goTypes = nil
	file_identity_v1_identity_proto_depIdxs = nil
}
