// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: authorizer/v1/authorizerService.proto

package authorizer

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_authorizer_v1_authorizerService_proto protoreflect.FileDescriptor

const file_authorizer_v1_authorizerService_proto_rawDesc = "" +
	"\n" +
	"%authorizer/v1/authorizerService.proto\x12\rauthorizer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x18authorizer/v1/auth.proto2\xe6\x04\n" +
	"\x11AuthorizerService\x12u\n" +
	"\vCheckAccess\x12!.authorizer.v1.CheckAccessRequest\x1a\".authorizer.v1.CheckAccessResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/access/check\x12u\n" +
	"\vGrantAccess\x12!.authorizer.v1.GrantAccessRequest\x1a\".authorizer.v1.GrantAccessResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/access/grant\x12y\n" +
	"\fRevokeAccess\x12\".authorizer.v1.RevokeAccessRequest\x1a#.authorizer.v1.RevokeAccessResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/access/revoke\x12q\n" +
	"\rGetUserAccess\x12#.authorizer.v1.GetUserAccessRequest\x1a\x19.authorizer.v1.UserAccess\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/access/{user_id}\x12u\n" +
	"\x0eListUserAccess\x12$.authorizer.v1.ListUserAccessRequest\x1a%.authorizer.v1.ListUserAccessResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/accessB:Z8github.com/AyuuSaxena/protos-go/authorizer/v1;authorizerb\x06proto3"

var file_authorizer_v1_authorizerService_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),     // 0: authorizer.v1.CheckAccessRequest
	(*GrantAccessRequest)(nil),     // 1: authorizer.v1.GrantAccessRequest
	(*RevokeAccessRequest)(nil),    // 2: authorizer.v1.RevokeAccessRequest
	(*GetUserAccessRequest)(nil),   // 3: authorizer.v1.GetUserAccessRequest
	(*ListUserAccessRequest)(nil),  // 4: authorizer.v1.ListUserAccessRequest
	(*CheckAccessResponse)(nil),    // 5: authorizer.v1.CheckAccessResponse
	(*GrantAccessResponse)(nil),    // 6: authorizer.v1.GrantAccessResponse
	(*RevokeAccessResponse)(nil),   // 7: authorizer.v1.RevokeAccessResponse
	(*UserAccess)(nil),             // 8: authorizer.v1.UserAccess
	(*ListUserAccessResponse)(nil), // 9: authorizer.v1.ListUserAccessResponse
}
var file_authorizer_v1_authorizerService_proto_depIdxs = []int32{
	0, // 0: authorizer.v1.AuthorizerService.CheckAccess:input_type -> authorizer.v1.CheckAccessRequest
	1, // 1: authorizer.v1.AuthorizerService.GrantAccess:input_type -> authorizer.v1.GrantAccessRequest
	2, // 2: authorizer.v1.AuthorizerService.RevokeAccess:input_type -> authorizer.v1.RevokeAccessRequest
	3, // 3: authorizer.v1.AuthorizerService.GetUserAccess:input_type -> authorizer.v1.GetUserAccessRequest
	4, // 4: authorizer.v1.AuthorizerService.ListUserAccess:input_type -> authorizer.v1.ListUserAccessRequest
	5, // 5: authorizer.v1.AuthorizerService.CheckAccess:output_type -> authorizer.v1.CheckAccessResponse
	6, // 6: authorizer.v1.AuthorizerService.GrantAccess:output_type -> authorizer.v1.GrantAccessResponse
	7, // 7: authorizer.v1.AuthorizerService.RevokeAccess:output_type -> authorizer.v1.RevokeAccessResponse
	8, // 8: authorizer.v1.AuthorizerService.GetUserAccess:output_type -> authorizer.v1.UserAccess
	9, // 9: authorizer.v1.AuthorizerService.ListUserAccess:output_type -> authorizer.v1.ListUserAccessResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authorizer_v1_authorizerService_proto_init() }
func file_authorizer_v1_authorizerService_proto_init() {
	if File_authorizer_v1_authorizerService_proto != nil {
		return
	}
	file_authorizer_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorizer_v1_authorizerService_proto_rawDesc), len(file_authorizer_v1_authorizerService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorizer_v1_authorizerService_proto_goTypes,
		DependencyIndexes: file_authorizer_v1_authorizerService_proto_depIdxs,
	}.Build()
	File_authorizer_v1_authorizerService_proto = out.File
	file_authorizer_v1_authorizerService_proto_goTypes = nil
	file_authorizer_v1_authorizerService_proto_depIdxs = nil
}
