// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: authorizer/v1/authorizerService.proto

package authorizer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthorizerService_CheckAccess_FullMethodName    = "/authorizer.v1.AuthorizerService/CheckAccess"
	AuthorizerService_GrantAccess_FullMethodName    = "/authorizer.v1.AuthorizerService/GrantAccess"
	AuthorizerService_RevokeAccess_FullMethodName   = "/authorizer.v1.AuthorizerService/RevokeAccess"
	AuthorizerService_GetUserAccess_FullMethodName  = "/authorizer.v1.AuthorizerService/GetUserAccess"
	AuthorizerService_ListUserAccess_FullMethodName = "/authorizer.v1.AuthorizerService/ListUserAccess"
)

// AuthorizerServiceClient is the client API for AuthorizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthorizerServiceClient interface {
	// CheckAccess verifies user permissions prior to login or action.
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
	// GrantAccess grants or updates permissions for a user on a service.
	GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*GrantAccessResponse, error)
	// RevokeAccess revokes access to a service for a user.
	RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error)
	// GetUserAccess retrieves a user's full access profile.
	GetUserAccess(ctx context.Context, in *GetUserAccessRequest, opts ...grpc.CallOption) (*UserAccess, error)
	// ListUserAccess lists access records with pagination.
	ListUserAccess(ctx context.Context, in *ListUserAccessRequest, opts ...grpc.CallOption) (*ListUserAccessResponse, error)
}

type authorizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizerServiceClient(cc grpc.ClientConnInterface) AuthorizerServiceClient {
	return &authorizerServiceClient{cc}
}

func (c *authorizerServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, AuthorizerService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizerServiceClient) GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...grpc.CallOption) (*GrantAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantAccessResponse)
	err := c.cc.Invoke(ctx, AuthorizerService_GrantAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizerServiceClient) RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...grpc.CallOption) (*RevokeAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeAccessResponse)
	err := c.cc.Invoke(ctx, AuthorizerService_RevokeAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizerServiceClient) GetUserAccess(ctx context.Context, in *GetUserAccessRequest, opts ...grpc.CallOption) (*UserAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserAccess)
	err := c.cc.Invoke(ctx, AuthorizerService_GetUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizerServiceClient) ListUserAccess(ctx context.Context, in *ListUserAccessRequest, opts ...grpc.CallOption) (*ListUserAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserAccessResponse)
	err := c.cc.Invoke(ctx, AuthorizerService_ListUserAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizerServiceServer is the server API for AuthorizerService service.
// All implementations must embed UnimplementedAuthorizerServiceServer
// for forward compatibility.
type AuthorizerServiceServer interface {
	// CheckAccess verifies user permissions prior to login or action.
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	// GrantAccess grants or updates permissions for a user on a service.
	GrantAccess(context.Context, *GrantAccessRequest) (*GrantAccessResponse, error)
	// RevokeAccess revokes access to a service for a user.
	RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error)
	// GetUserAccess retrieves a user's full access profile.
	GetUserAccess(context.Context, *GetUserAccessRequest) (*UserAccess, error)
	// ListUserAccess lists access records with pagination.
	ListUserAccess(context.Context, *ListUserAccessRequest) (*ListUserAccessResponse, error)
	mustEmbedUnimplementedAuthorizerServiceServer()
}

// UnimplementedAuthorizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizerServiceServer struct{}

func (UnimplementedAuthorizerServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedAuthorizerServiceServer) GrantAccess(context.Context, *GrantAccessRequest) (*GrantAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantAccess not implemented")
}
func (UnimplementedAuthorizerServiceServer) RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedAuthorizerServiceServer) GetUserAccess(context.Context, *GetUserAccessRequest) (*UserAccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAccess not implemented")
}
func (UnimplementedAuthorizerServiceServer) ListUserAccess(context.Context, *ListUserAccessRequest) (*ListUserAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserAccess not implemented")
}
func (UnimplementedAuthorizerServiceServer) mustEmbedUnimplementedAuthorizerServiceServer() {}
func (UnimplementedAuthorizerServiceServer) testEmbeddedByValue()                           {}

// UnsafeAuthorizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizerServiceServer will
// result in compilation errors.
type UnsafeAuthorizerServiceServer interface {
	mustEmbedUnimplementedAuthorizerServiceServer()
}

func RegisterAuthorizerServiceServer(s grpc.ServiceRegistrar, srv AuthorizerServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthorizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorizerService_ServiceDesc, srv)
}

func _AuthorizerService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizerService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizerService_GrantAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).GrantAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizerService_GrantAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).GrantAccess(ctx, req.(*GrantAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizerService_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizerService_RevokeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).RevokeAccess(ctx, req.(*RevokeAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizerService_GetUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).GetUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizerService_GetUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).GetUserAccess(ctx, req.(*GetUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizerService_ListUserAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).ListUserAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizerService_ListUserAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).ListUserAccess(ctx, req.(*ListUserAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizerService_ServiceDesc is the grpc.ServiceDesc for AuthorizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authorizer.v1.AuthorizerService",
	HandlerType: (*AuthorizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccess",
			Handler:    _AuthorizerService_CheckAccess_Handler,
		},
		{
			MethodName: "GrantAccess",
			Handler:    _AuthorizerService_GrantAccess_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _AuthorizerService_RevokeAccess_Handler,
		},
		{
			MethodName: "GetUserAccess",
			Handler:    _AuthorizerService_GetUserAccess_Handler,
		},
		{
			MethodName: "ListUserAccess",
			Handler:    _AuthorizerService_ListUserAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorizer/v1/authorizerService.proto",
}
