// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: authorizer/v1/auth.proto

package authorizer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTokenPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Site  string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	// @gotags: `json:"siteId,omitempty" bson:"siteId,omitempty"`
	SiteId *string `protobuf:"bytes,2,opt,name=site_id,json=siteId,proto3,oneof" json:"siteId,omitempty" bson:"siteId,omitempty"`
	Id     string  `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: `json:"userId,omitempty" bson:"userId,omitempty"`
	UserId string  `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"userId,omitempty" bson:"userId,omitempty"`
	Email  *string `protobuf:"bytes,5,opt,name=email,proto3,oneof" json:"email,omitempty"`
	// @gotags: `json:"phoneNumber,omitempty" bson:"phoneNumber,omitempty"`
	PhoneNumber *string `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3,oneof" json:"phoneNumber,omitempty" bson:"phoneNumber,omitempty"`
	// @gotags: `json:"phoneCode,omitempty" bson:"phoneCode,omitempty"`
	PhoneCode   *uint32 `protobuf:"varint,7,opt,name=phone_code,json=phoneCode,proto3,oneof" json:"phoneCode,omitempty" bson:"phoneCode,omitempty"`
	Ipaddresses string  `protobuf:"bytes,8,opt,name=ipaddresses,proto3" json:"ipaddresses,omitempty"`
	// @gotags: `json:"countryCode,omitempty" bson:"countryCode,omitempty"`
	CountryCode string  `protobuf:"bytes,9,opt,name=country_code,json=countryCode,proto3" json:"countryCode,omitempty" bson:"countryCode,omitempty"`
	Postalcode  *string `protobuf:"bytes,10,opt,name=postalcode,proto3,oneof" json:"postalcode,omitempty"`
	// @gotags: `json:"deviceId,omitempty" bson:"deviceId,omitempty"`
	DeviceId *string `protobuf:"bytes,12,opt,name=device_id,json=deviceId,proto3,oneof" json:"deviceId,omitempty" bson:"deviceId,omitempty"`
	// @gotags: `json:"deviceLimitExceeded,omitempty" bson:"deviceLimitExceeded,omitempty"`
	DeviceLimitExceeded *bool `protobuf:"varint,13,opt,name=device_limit_exceeded,json=deviceLimitExceeded,proto3,oneof" json:"deviceLimitExceeded,omitempty" bson:"deviceLimitExceeded,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserTokenPayload) Reset() {
	*x = UserTokenPayload{}
	mi := &file_authorizer_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTokenPayload) ProtoMessage() {}

func (x *UserTokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_authorizer_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTokenPayload.ProtoReflect.Descriptor instead.
func (*UserTokenPayload) Descriptor() ([]byte, []int) {
	return file_authorizer_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserTokenPayload) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *UserTokenPayload) GetSiteId() string {
	if x != nil && x.SiteId != nil {
		return *x.SiteId
	}
	return ""
}

func (x *UserTokenPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserTokenPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserTokenPayload) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserTokenPayload) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

func (x *UserTokenPayload) GetPhoneCode() uint32 {
	if x != nil && x.PhoneCode != nil {
		return *x.PhoneCode
	}
	return 0
}

func (x *UserTokenPayload) GetIpaddresses() string {
	if x != nil {
		return x.Ipaddresses
	}
	return ""
}

func (x *UserTokenPayload) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UserTokenPayload) GetPostalcode() string {
	if x != nil && x.Postalcode != nil {
		return *x.Postalcode
	}
	return ""
}

func (x *UserTokenPayload) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *UserTokenPayload) GetDeviceLimitExceeded() bool {
	if x != nil && x.DeviceLimitExceeded != nil {
		return *x.DeviceLimitExceeded
	}
	return false
}

var File_authorizer_v1_auth_proto protoreflect.FileDescriptor

const file_authorizer_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18authorizer/v1/auth.proto\x12\rauthorizer.v1\"\x86\x04\n" +
	"\x10UserTokenPayload\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x1c\n" +
	"\asite_id\x18\x02 \x01(\tH\x00R\x06siteId\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x19\n" +
	"\x05email\x18\x05 \x01(\tH\x01R\x05email\x88\x01\x01\x12&\n" +
	"\fphone_number\x18\x06 \x01(\tH\x02R\vphoneNumber\x88\x01\x01\x12\"\n" +
	"\n" +
	"phone_code\x18\a \x01(\rH\x03R\tphoneCode\x88\x01\x01\x12 \n" +
	"\vipaddresses\x18\b \x01(\tR\vipaddresses\x12!\n" +
	"\fcountry_code\x18\t \x01(\tR\vcountryCode\x12#\n" +
	"\n" +
	"postalcode\x18\n" +
	" \x01(\tH\x04R\n" +
	"postalcode\x88\x01\x01\x12 \n" +
	"\tdevice_id\x18\f \x01(\tH\x05R\bdeviceId\x88\x01\x01\x127\n" +
	"\x15device_limit_exceeded\x18\r \x01(\bH\x06R\x13deviceLimitExceeded\x88\x01\x01B\n" +
	"\n" +
	"\b_site_idB\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_phone_numberB\r\n" +
	"\v_phone_codeB\r\n" +
	"\v_postalcodeB\f\n" +
	"\n" +
	"_device_idB\x18\n" +
	"\x16_device_limit_exceededB=Z;github.com/AyuuSaxena/my-protos-go/authorizer/v1;authorizerb\x06proto3"

var (
	file_authorizer_v1_auth_proto_rawDescOnce sync.Once
	file_authorizer_v1_auth_proto_rawDescData []byte
)

func file_authorizer_v1_auth_proto_rawDescGZIP() []byte {
	file_authorizer_v1_auth_proto_rawDescOnce.Do(func() {
		file_authorizer_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorizer_v1_auth_proto_rawDesc), len(file_authorizer_v1_auth_proto_rawDesc)))
	})
	return file_authorizer_v1_auth_proto_rawDescData
}

var file_authorizer_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authorizer_v1_auth_proto_goTypes = []any{
	(*UserTokenPayload)(nil), // 0: authorizer.v1.UserTokenPayload
}
var file_authorizer_v1_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authorizer_v1_auth_proto_init() }
func file_authorizer_v1_auth_proto_init() {
	if File_authorizer_v1_auth_proto != nil {
		return
	}
	file_authorizer_v1_auth_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorizer_v1_auth_proto_rawDesc), len(file_authorizer_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authorizer_v1_auth_proto_goTypes,
		DependencyIndexes: file_authorizer_v1_auth_proto_depIdxs,
		MessageInfos:      file_authorizer_v1_auth_proto_msgTypes,
	}.Build()
	File_authorizer_v1_auth_proto = out.File
	file_authorizer_v1_auth_proto_goTypes = nil
	file_authorizer_v1_auth_proto_depIdxs = nil
}
