// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: content/v1/rom.proto

package content

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RomMetadata struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug        string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Console     string                 `protobuf:"bytes,5,opt,name=console,proto3" json:"console,omitempty"`
	// @gotags: `json:"consoleFullName,omitempty" bson:"consoleFullName,omitempty"`
	ConsoleFullName string `protobuf:"bytes,6,opt,name=console_full_name,json=consoleFullName,proto3" json:"consoleFullName,omitempty" bson:"consoleFullName,omitempty"`
	// @gotags: `json:"fileName,omitempty" bson:"fileName,omitempty"`
	FileName string `protobuf:"bytes,7,opt,name=file_name,json=fileName,proto3" json:"fileName,omitempty" bson:"fileName,omitempty"`
	// @gotags: `json:"originalFileName,omitempty" bson:"originalFileName,omitempty"`
	OriginalFileName string `protobuf:"bytes,8,opt,name=original_file_name,json=originalFileName,proto3" json:"originalFileName,omitempty" bson:"originalFileName,omitempty"`
	// @gotags: `json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	FileExtension string `protobuf:"bytes,9,opt,name=file_extension,json=fileExtension,proto3" json:"fileExtension,omitempty" bson:"fileExtension,omitempty"`
	// @gotags: `json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	MimeType string `protobuf:"bytes,10,opt,name=mime_type,json=mimeType,proto3" json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	// @gotags: `json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	SizeBytes int64 `protobuf:"varint,11,opt,name=size_bytes,json=sizeBytes,proto3" json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	// @gotags: `json:"checksumMD5,omitempty" bson:"checksumMD5,omitempty"`
	ChecksumMd5 string `protobuf:"bytes,12,opt,name=checksum_md5,json=checksumMd5,proto3" json:"checksumMD5,omitempty" bson:"checksumMD5,omitempty"`
	// @gotags: `json:"checksumSHA256,omitempty" bson:"checksumSHA256,omitempty"`
	ChecksumSha256 string `protobuf:"bytes,13,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksumSHA256,omitempty" bson:"checksumSHA256,omitempty"`
	// @gotags: `json:"storageBucket,omitempty" bson:"storageBucket,omitempty"`
	StorageBucket string `protobuf:"bytes,14,opt,name=storage_bucket,json=storageBucket,proto3" json:"storageBucket,omitempty" bson:"storageBucket,omitempty"`
	// @gotags: `json:"storageKey,omitempty" bson:"storageKey,omitempty"`
	StorageKey string `protobuf:"bytes,15,opt,name=storage_key,json=storageKey,proto3" json:"storageKey,omitempty" bson:"storageKey,omitempty"`
	// @gotags: `json:"storageUrl,omitempty" bson:"storageUrl,omitempty"`
	StorageUrl string `protobuf:"bytes,16,opt,name=storage_url,json=storageUrl,proto3" json:"storageUrl,omitempty" bson:"storageUrl,omitempty"`
	Developer  string `protobuf:"bytes,17,opt,name=developer,proto3" json:"developer,omitempty"`
	Publisher  string `protobuf:"bytes,18,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32    `protobuf:"varint,19,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	Genre       string   `protobuf:"bytes,20,opt,name=genre,proto3" json:"genre,omitempty"`
	Region      string   `protobuf:"bytes,21,opt,name=region,proto3" json:"region,omitempty"`
	Players     int32    `protobuf:"varint,22,opt,name=players,proto3" json:"players,omitempty"`
	Rating      string   `protobuf:"bytes,23,opt,name=rating,proto3" json:"rating,omitempty"`
	Tags        []string `protobuf:"bytes,24,rep,name=tags,proto3" json:"tags,omitempty"`
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool   `protobuf:"varint,25,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	Status   string `protobuf:"bytes,26,opt,name=status,proto3" json:"status,omitempty"`
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,27,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// @gotags: `json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	UploaderUsername string `protobuf:"bytes,28,opt,name=uploader_username,json=uploaderUsername,proto3" json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt string `protobuf:"bytes,29,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	// @gotags: `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,30,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	// @gotags: `json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	DownloadUrl   string `protobuf:"bytes,31,opt,name=download_url,json=downloadUrl,proto3" json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomMetadata) Reset() {
	*x = RomMetadata{}
	mi := &file_content_v1_rom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomMetadata) ProtoMessage() {}

func (x *RomMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomMetadata.ProtoReflect.Descriptor instead.
func (*RomMetadata) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{0}
}

func (x *RomMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RomMetadata) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *RomMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RomMetadata) GetConsole() string {
	if x != nil {
		return x.Console
	}
	return ""
}

func (x *RomMetadata) GetConsoleFullName() string {
	if x != nil {
		return x.ConsoleFullName
	}
	return ""
}

func (x *RomMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RomMetadata) GetOriginalFileName() string {
	if x != nil {
		return x.OriginalFileName
	}
	return ""
}

func (x *RomMetadata) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *RomMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *RomMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *RomMetadata) GetChecksumMd5() string {
	if x != nil {
		return x.ChecksumMd5
	}
	return ""
}

func (x *RomMetadata) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *RomMetadata) GetStorageBucket() string {
	if x != nil {
		return x.StorageBucket
	}
	return ""
}

func (x *RomMetadata) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *RomMetadata) GetStorageUrl() string {
	if x != nil {
		return x.StorageUrl
	}
	return ""
}

func (x *RomMetadata) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *RomMetadata) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *RomMetadata) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *RomMetadata) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *RomMetadata) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RomMetadata) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *RomMetadata) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *RomMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RomMetadata) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *RomMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RomMetadata) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *RomMetadata) GetUploaderUsername() string {
	if x != nil {
		return x.UploaderUsername
	}
	return ""
}

func (x *RomMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RomMetadata) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RomMetadata) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type RomGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomGetRequest) Reset() {
	*x = RomGetRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomGetRequest) ProtoMessage() {}

func (x *RomGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomGetRequest.ProtoReflect.Descriptor instead.
func (*RomGetRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{1}
}

func (x *RomGetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomGetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomGetRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type RomDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Slug          *string                `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDownloadRequest) Reset() {
	*x = RomDownloadRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDownloadRequest) ProtoMessage() {}

func (x *RomDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDownloadRequest.ProtoReflect.Descriptor instead.
func (*RomDownloadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{2}
}

func (x *RomDownloadRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RomDownloadRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomDownloadRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_content_v1_rom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RomListRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Console *string                `protobuf:"bytes,2,opt,name=console,proto3,oneof" json:"console,omitempty"`
	Genre   *string                `protobuf:"bytes,3,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
	Region  *string                `protobuf:"bytes,4,opt,name=region,proto3,oneof" json:"region,omitempty"`
	// @gotags: `json:"searchQuery,omitempty" bson:"searchQuery,omitempty"`
	SearchQuery *string `protobuf:"bytes,5,opt,name=search_query,json=searchQuery,proto3,oneof" json:"searchQuery,omitempty" bson:"searchQuery,omitempty"`
	Page        *int32  `protobuf:"varint,6,opt,name=page,proto3,oneof" json:"page,omitempty"`
	// @gotags: `json:"pageSize,omitempty" bson:"pageSize,omitempty"`
	PageSize *int32 `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3,oneof" json:"pageSize,omitempty" bson:"pageSize,omitempty"`
	// @gotags: `json:"sortBy,omitempty" bson:"sortBy,omitempty"`
	SortBy *string `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sortBy,omitempty" bson:"sortBy,omitempty"`
	// @gotags: `json:"sortOrder,omitempty" bson:"sortOrder,omitempty"`
	SortOrder     *string `protobuf:"bytes,9,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sortOrder,omitempty" bson:"sortOrder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomListRequest) Reset() {
	*x = RomListRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomListRequest) ProtoMessage() {}

func (x *RomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomListRequest.ProtoReflect.Descriptor instead.
func (*RomListRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{4}
}

func (x *RomListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *RomListRequest) GetConsole() string {
	if x != nil && x.Console != nil {
		return *x.Console
	}
	return ""
}

func (x *RomListRequest) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *RomListRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *RomListRequest) GetSearchQuery() string {
	if x != nil && x.SearchQuery != nil {
		return *x.SearchQuery
	}
	return ""
}

func (x *RomListRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *RomListRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *RomListRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *RomListRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

type RomListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Roms  []*RomMetadata         `protobuf:"bytes,1,rep,name=roms,proto3" json:"roms,omitempty"`
	// @gotags: `json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	TotalCount int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	Page       int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// @gotags: `json:"pageSize,omitempty" bson:"pageSize,omitempty"`
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty" bson:"pageSize,omitempty"`
	// @gotags: `json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	TotalPages    int32 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomListResponse) Reset() {
	*x = RomListResponse{}
	mi := &file_content_v1_rom_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomListResponse) ProtoMessage() {}

func (x *RomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomListResponse.ProtoReflect.Descriptor instead.
func (*RomListResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{5}
}

func (x *RomListResponse) GetRoms() []*RomMetadata {
	if x != nil {
		return x.Roms
	}
	return nil
}

func (x *RomListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *RomListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RomListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *RomListResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type FileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: `json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	// @gotags: `json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	SizeBytes   int64  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Console     string `protobuf:"bytes,6,opt,name=console,proto3" json:"console,omitempty"`
	Developer   string `protobuf:"bytes,7,opt,name=developer,proto3" json:"developer,omitempty"`
	Publisher   string `protobuf:"bytes,8,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32    `protobuf:"varint,9,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	Genre       string   `protobuf:"bytes,10,opt,name=genre,proto3" json:"genre,omitempty"`
	Region      string   `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	Players     int32    `protobuf:"varint,12,opt,name=players,proto3" json:"players,omitempty"`
	Rating      string   `protobuf:"bytes,13,opt,name=rating,proto3" json:"rating,omitempty"`
	Tags        []string `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool `protobuf:"varint,15,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// @gotags: `json:"customKey,omitempty" bson:"customKey,omitempty"`
	CustomKey string `protobuf:"bytes,16,opt,name=custom_key,json=customKey,proto3" json:"customKey,omitempty" bson:"customKey,omitempty"`
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,17,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// @gotags: `json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	UploaderUsername string `protobuf:"bytes,18,opt,name=uploader_username,json=uploaderUsername,proto3" json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_content_v1_rom_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{6}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FileInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FileInfo) GetConsole() string {
	if x != nil {
		return x.Console
	}
	return ""
}

func (x *FileInfo) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *FileInfo) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *FileInfo) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *FileInfo) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *FileInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *FileInfo) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *FileInfo) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *FileInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FileInfo) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *FileInfo) GetCustomKey() string {
	if x != nil {
		return x.CustomKey
	}
	return ""
}

func (x *FileInfo) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *FileInfo) GetUploaderUsername() string {
	if x != nil {
		return x.UploaderUsername
	}
	return ""
}

type RomUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestData:
	//
	//	*RomUploadRequest_FileInfo
	//	*RomUploadRequest_ChunkData
	RequestData   isRomUploadRequest_RequestData `protobuf_oneof:"request_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUploadRequest) Reset() {
	*x = RomUploadRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadRequest) ProtoMessage() {}

func (x *RomUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadRequest.ProtoReflect.Descriptor instead.
func (*RomUploadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{7}
}

func (x *RomUploadRequest) GetRequestData() isRomUploadRequest_RequestData {
	if x != nil {
		return x.RequestData
	}
	return nil
}

func (x *RomUploadRequest) GetFileInfo() *FileInfo {
	if x != nil {
		if x, ok := x.RequestData.(*RomUploadRequest_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

func (x *RomUploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.RequestData.(*RomUploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isRomUploadRequest_RequestData interface {
	isRomUploadRequest_RequestData()
}

type RomUploadRequest_FileInfo struct {
	// @gotags: `json:"fileInfo,omitempty" bson:"fileInfo,omitempty"`
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof" json:"fileInfo,omitempty" bson:"fileInfo,omitempty"`
}

type RomUploadRequest_ChunkData struct {
	// @gotags: `json:"chunkData,omitempty" bson:"chunkData,omitempty"`
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof" json:"chunkData,omitempty" bson:"chunkData,omitempty"`
}

func (*RomUploadRequest_FileInfo) isRomUploadRequest_RequestData() {}

func (*RomUploadRequest_ChunkData) isRomUploadRequest_RequestData() {}

type RomUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rom           *RomMetadata           `protobuf:"bytes,1,opt,name=rom,proto3" json:"rom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUploadResponse) Reset() {
	*x = RomUploadResponse{}
	mi := &file_content_v1_rom_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUploadResponse) ProtoMessage() {}

func (x *RomUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUploadResponse.ProtoReflect.Descriptor instead.
func (*RomUploadResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{8}
}

func (x *RomUploadResponse) GetRom() *RomMetadata {
	if x != nil {
		return x.Rom
	}
	return nil
}

type RomUpdateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Description *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Console     *string                `protobuf:"bytes,4,opt,name=console,proto3,oneof" json:"console,omitempty"`
	Developer   *string                `protobuf:"bytes,5,opt,name=developer,proto3,oneof" json:"developer,omitempty"`
	Publisher   *string                `protobuf:"bytes,6,opt,name=publisher,proto3,oneof" json:"publisher,omitempty"`
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear *int32   `protobuf:"varint,7,opt,name=release_year,json=releaseYear,proto3,oneof" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	Genre       *string  `protobuf:"bytes,8,opt,name=genre,proto3,oneof" json:"genre,omitempty"`
	Region      *string  `protobuf:"bytes,9,opt,name=region,proto3,oneof" json:"region,omitempty"`
	Players     *int32   `protobuf:"varint,10,opt,name=players,proto3,oneof" json:"players,omitempty"`
	Rating      *string  `protobuf:"bytes,11,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	Tags        []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic      *bool `protobuf:"varint,13,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomUpdateRequest) Reset() {
	*x = RomUpdateRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomUpdateRequest) ProtoMessage() {}

func (x *RomUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomUpdateRequest.ProtoReflect.Descriptor instead.
func (*RomUpdateRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{9}
}

func (x *RomUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomUpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *RomUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RomUpdateRequest) GetConsole() string {
	if x != nil && x.Console != nil {
		return *x.Console
	}
	return ""
}

func (x *RomUpdateRequest) GetDeveloper() string {
	if x != nil && x.Developer != nil {
		return *x.Developer
	}
	return ""
}

func (x *RomUpdateRequest) GetPublisher() string {
	if x != nil && x.Publisher != nil {
		return *x.Publisher
	}
	return ""
}

func (x *RomUpdateRequest) GetReleaseYear() int32 {
	if x != nil && x.ReleaseYear != nil {
		return *x.ReleaseYear
	}
	return 0
}

func (x *RomUpdateRequest) GetGenre() string {
	if x != nil && x.Genre != nil {
		return *x.Genre
	}
	return ""
}

func (x *RomUpdateRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *RomUpdateRequest) GetPlayers() int32 {
	if x != nil && x.Players != nil {
		return *x.Players
	}
	return 0
}

func (x *RomUpdateRequest) GetRating() string {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return ""
}

func (x *RomUpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RomUpdateRequest) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

type RomDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: `json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	HardDelete    bool `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDeleteRequest) Reset() {
	*x = RomDeleteRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDeleteRequest) ProtoMessage() {}

func (x *RomDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDeleteRequest.ProtoReflect.Descriptor instead.
func (*RomDeleteRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{10}
}

func (x *RomDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomDeleteRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

type RomDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomDeleteResponse) Reset() {
	*x = RomDeleteResponse{}
	mi := &file_content_v1_rom_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomDeleteResponse) ProtoMessage() {}

func (x *RomDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomDeleteResponse.ProtoReflect.Descriptor instead.
func (*RomDeleteResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{11}
}

func (x *RomDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RomDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RomShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: `json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	ExpiresInSec  int32 `protobuf:"varint,2,opt,name=expires_in_sec,json=expiresInSec,proto3" json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomShareRequest) Reset() {
	*x = RomShareRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomShareRequest) ProtoMessage() {}

func (x *RomShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomShareRequest.ProtoReflect.Descriptor instead.
func (*RomShareRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{12}
}

func (x *RomShareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomShareRequest) GetExpiresInSec() int32 {
	if x != nil {
		return x.ExpiresInSec
	}
	return 0
}

type RomShareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: `json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	DownloadUrl string `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	// @gotags: `json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	ExpiresAt     string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RomShareResponse) Reset() {
	*x = RomShareResponse{}
	mi := &file_content_v1_rom_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RomShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RomShareResponse) ProtoMessage() {}

func (x *RomShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RomShareResponse.ProtoReflect.Descriptor instead.
func (*RomShareResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{13}
}

func (x *RomShareResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RomShareResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *RomShareResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type ConsoleInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// @gotags: `json:"fullName,omitempty" bson:"fullName,omitempty"`
	FullName     string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"fullName,omitempty" bson:"fullName,omitempty"`
	Extensions   []string `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	Manufacturer string   `protobuf:"bytes,4,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	// @gotags: `json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	ReleaseYear int32 `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"releaseYear,omitempty" bson:"releaseYear,omitempty"`
	// @gotags: `json:"contentCount,omitempty" bson:"contentCount,omitempty"`
	ContentCount  int64 `protobuf:"varint,6,opt,name=content_count,json=contentCount,proto3" json:"contentCount,omitempty" bson:"contentCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleInfo) Reset() {
	*x = ConsoleInfo{}
	mi := &file_content_v1_rom_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInfo) ProtoMessage() {}

func (x *ConsoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleInfo.ProtoReflect.Descriptor instead.
func (*ConsoleInfo) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{14}
}

func (x *ConsoleInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConsoleInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ConsoleInfo) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *ConsoleInfo) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *ConsoleInfo) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *ConsoleInfo) GetContentCount() int64 {
	if x != nil {
		return x.ContentCount
	}
	return 0
}

type ListConsolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolesRequest) Reset() {
	*x = ListConsolesRequest{}
	mi := &file_content_v1_rom_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolesRequest) ProtoMessage() {}

func (x *ListConsolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolesRequest.ProtoReflect.Descriptor instead.
func (*ListConsolesRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{15}
}

type ListConsolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consoles      []*ConsoleInfo         `protobuf:"bytes,1,rep,name=consoles,proto3" json:"consoles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolesResponse) Reset() {
	*x = ListConsolesResponse{}
	mi := &file_content_v1_rom_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolesResponse) ProtoMessage() {}

func (x *ListConsolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_rom_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolesResponse.ProtoReflect.Descriptor instead.
func (*ListConsolesResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_rom_proto_rawDescGZIP(), []int{16}
}

func (x *ListConsolesResponse) GetConsoles() []*ConsoleInfo {
	if x != nil {
		return x.Consoles
	}
	return nil
}

var File_content_v1_rom_proto protoreflect.FileDescriptor

const file_content_v1_rom_proto_rawDesc = "" +
	"\n" +
	"\x14content/v1/rom.proto\x12\n" +
	"content.v1\"\xc9\a\n" +
	"\vRomMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aconsole\x18\x05 \x01(\tR\aconsole\x12*\n" +
	"\x11console_full_name\x18\x06 \x01(\tR\x0fconsoleFullName\x12\x1b\n" +
	"\tfile_name\x18\a \x01(\tR\bfileName\x12,\n" +
	"\x12original_file_name\x18\b \x01(\tR\x10originalFileName\x12%\n" +
	"\x0efile_extension\x18\t \x01(\tR\rfileExtension\x12\x1b\n" +
	"\tmime_type\x18\n" +
	" \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\v \x01(\x03R\tsizeBytes\x12!\n" +
	"\fchecksum_md5\x18\f \x01(\tR\vchecksumMd5\x12'\n" +
	"\x0fchecksum_sha256\x18\r \x01(\tR\x0echecksumSha256\x12%\n" +
	"\x0estorage_bucket\x18\x0e \x01(\tR\rstorageBucket\x12\x1f\n" +
	"\vstorage_key\x18\x0f \x01(\tR\n" +
	"storageKey\x12\x1f\n" +
	"\vstorage_url\x18\x10 \x01(\tR\n" +
	"storageUrl\x12\x1c\n" +
	"\tdeveloper\x18\x11 \x01(\tR\tdeveloper\x12\x1c\n" +
	"\tpublisher\x18\x12 \x01(\tR\tpublisher\x12!\n" +
	"\frelease_year\x18\x13 \x01(\x05R\vreleaseYear\x12\x14\n" +
	"\x05genre\x18\x14 \x01(\tR\x05genre\x12\x16\n" +
	"\x06region\x18\x15 \x01(\tR\x06region\x12\x18\n" +
	"\aplayers\x18\x16 \x01(\x05R\aplayers\x12\x16\n" +
	"\x06rating\x18\x17 \x01(\tR\x06rating\x12\x12\n" +
	"\x04tags\x18\x18 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x19 \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x1a \x01(\tR\x06status\x12\x1f\n" +
	"\vuploader_id\x18\x1b \x01(\tR\n" +
	"uploaderId\x12+\n" +
	"\x11uploader_username\x18\x1c \x01(\tR\x10uploaderUsername\x12\x1d\n" +
	"\n" +
	"created_at\x18\x1d \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x1e \x01(\tR\tupdatedAt\x12!\n" +
	"\fdownload_url\x18\x1f \x01(\tR\vdownloadUrl\"o\n" +
	"\rRomGetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x02R\x04slug\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slug\"t\n" +
	"\x12RomDownloadRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x02R\x04slug\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slug\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x92\x03\n" +
	"\x0eRomListRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aconsole\x18\x02 \x01(\tH\x01R\aconsole\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\x03 \x01(\tH\x02R\x05genre\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x04 \x01(\tH\x03R\x06region\x88\x01\x01\x12&\n" +
	"\fsearch_query\x18\x05 \x01(\tH\x04R\vsearchQuery\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x06 \x01(\x05H\x05R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\a \x01(\x05H\x06R\bpageSize\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\b \x01(\tH\aR\x06sortBy\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\t \x01(\tH\bR\tsortOrder\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_consoleB\b\n" +
	"\x06_genreB\t\n" +
	"\a_regionB\x0f\n" +
	"\r_search_queryB\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_sizeB\n" +
	"\n" +
	"\b_sort_byB\r\n" +
	"\v_sort_order\"\xb1\x01\n" +
	"\x0fRomListResponse\x12+\n" +
	"\x04roms\x18\x01 \x03(\v2\x17.content.v1.RomMetadataR\x04roms\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\x89\x04\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aconsole\x18\x06 \x01(\tR\aconsole\x12\x1c\n" +
	"\tdeveloper\x18\a \x01(\tR\tdeveloper\x12\x1c\n" +
	"\tpublisher\x18\b \x01(\tR\tpublisher\x12!\n" +
	"\frelease_year\x18\t \x01(\x05R\vreleaseYear\x12\x14\n" +
	"\x05genre\x18\n" +
	" \x01(\tR\x05genre\x12\x16\n" +
	"\x06region\x18\v \x01(\tR\x06region\x12\x18\n" +
	"\aplayers\x18\f \x01(\x05R\aplayers\x12\x16\n" +
	"\x06rating\x18\r \x01(\tR\x06rating\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x0f \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"custom_key\x18\x10 \x01(\tR\tcustomKey\x12\x1f\n" +
	"\vuploader_id\x18\x11 \x01(\tR\n" +
	"uploaderId\x12+\n" +
	"\x11uploader_username\x18\x12 \x01(\tR\x10uploaderUsername\"x\n" +
	"\x10RomUploadRequest\x123\n" +
	"\tfile_info\x18\x01 \x01(\v2\x14.content.v1.FileInfoH\x00R\bfileInfo\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x0e\n" +
	"\frequest_data\">\n" +
	"\x11RomUploadResponse\x12)\n" +
	"\x03rom\x18\x01 \x01(\v2\x17.content.v1.RomMetadataR\x03rom\"\xa8\x04\n" +
	"\x10RomUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\aconsole\x18\x04 \x01(\tH\x02R\aconsole\x88\x01\x01\x12!\n" +
	"\tdeveloper\x18\x05 \x01(\tH\x03R\tdeveloper\x88\x01\x01\x12!\n" +
	"\tpublisher\x18\x06 \x01(\tH\x04R\tpublisher\x88\x01\x01\x12&\n" +
	"\frelease_year\x18\a \x01(\x05H\x05R\vreleaseYear\x88\x01\x01\x12\x19\n" +
	"\x05genre\x18\b \x01(\tH\x06R\x05genre\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\t \x01(\tH\aR\x06region\x88\x01\x01\x12\x1d\n" +
	"\aplayers\x18\n" +
	" \x01(\x05H\bR\aplayers\x88\x01\x01\x12\x1b\n" +
	"\x06rating\x18\v \x01(\tH\tR\x06rating\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12 \n" +
	"\tis_public\x18\r \x01(\bH\n" +
	"R\bisPublic\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_consoleB\f\n" +
	"\n" +
	"_developerB\f\n" +
	"\n" +
	"_publisherB\x0f\n" +
	"\r_release_yearB\b\n" +
	"\x06_genreB\t\n" +
	"\a_regionB\n" +
	"\n" +
	"\b_playersB\t\n" +
	"\a_ratingB\f\n" +
	"\n" +
	"_is_public\"C\n" +
	"\x10RomDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\"G\n" +
	"\x11RomDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x0fRomShareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eexpires_in_sec\x18\x02 \x01(\x05R\fexpiresInSec\"d\n" +
	"\x10RomShareResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"\xc8\x01\n" +
	"\vConsoleInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x1e\n" +
	"\n" +
	"extensions\x18\x03 \x03(\tR\n" +
	"extensions\x12\"\n" +
	"\fmanufacturer\x18\x04 \x01(\tR\fmanufacturer\x12!\n" +
	"\frelease_year\x18\x05 \x01(\x05R\vreleaseYear\x12#\n" +
	"\rcontent_count\x18\x06 \x01(\x03R\fcontentCount\"\x15\n" +
	"\x13ListConsolesRequest\"K\n" +
	"\x14ListConsolesResponse\x123\n" +
	"\bconsoles\x18\x01 \x03(\v2\x17.content.v1.ConsoleInfoR\bconsolesB7Z5github.com/AyuuSaxena/my-protos-go/content/v1;contentb\x06proto3"

var (
	file_content_v1_rom_proto_rawDescOnce sync.Once
	file_content_v1_rom_proto_rawDescData []byte
)

func file_content_v1_rom_proto_rawDescGZIP() []byte {
	file_content_v1_rom_proto_rawDescOnce.Do(func() {
		file_content_v1_rom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_v1_rom_proto_rawDesc), len(file_content_v1_rom_proto_rawDesc)))
	})
	return file_content_v1_rom_proto_rawDescData
}

var file_content_v1_rom_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_content_v1_rom_proto_goTypes = []any{
	(*RomMetadata)(nil),          // 0: content.v1.RomMetadata
	(*RomGetRequest)(nil),        // 1: content.v1.RomGetRequest
	(*RomDownloadRequest)(nil),   // 2: content.v1.RomDownloadRequest
	(*FileChunk)(nil),            // 3: content.v1.FileChunk
	(*RomListRequest)(nil),       // 4: content.v1.RomListRequest
	(*RomListResponse)(nil),      // 5: content.v1.RomListResponse
	(*FileInfo)(nil),             // 6: content.v1.FileInfo
	(*RomUploadRequest)(nil),     // 7: content.v1.RomUploadRequest
	(*RomUploadResponse)(nil),    // 8: content.v1.RomUploadResponse
	(*RomUpdateRequest)(nil),     // 9: content.v1.RomUpdateRequest
	(*RomDeleteRequest)(nil),     // 10: content.v1.RomDeleteRequest
	(*RomDeleteResponse)(nil),    // 11: content.v1.RomDeleteResponse
	(*RomShareRequest)(nil),      // 12: content.v1.RomShareRequest
	(*RomShareResponse)(nil),     // 13: content.v1.RomShareResponse
	(*ConsoleInfo)(nil),          // 14: content.v1.ConsoleInfo
	(*ListConsolesRequest)(nil),  // 15: content.v1.ListConsolesRequest
	(*ListConsolesResponse)(nil), // 16: content.v1.ListConsolesResponse
}
var file_content_v1_rom_proto_depIdxs = []int32{
	0,  // 0: content.v1.RomListResponse.roms:type_name -> content.v1.RomMetadata
	6,  // 1: content.v1.RomUploadRequest.file_info:type_name -> content.v1.FileInfo
	0,  // 2: content.v1.RomUploadResponse.rom:type_name -> content.v1.RomMetadata
	14, // 3: content.v1.ListConsolesResponse.consoles:type_name -> content.v1.ConsoleInfo
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_content_v1_rom_proto_init() }
func file_content_v1_rom_proto_init() {
	if File_content_v1_rom_proto != nil {
		return
	}
	file_content_v1_rom_proto_msgTypes[1].OneofWrappers = []any{}
	file_content_v1_rom_proto_msgTypes[2].OneofWrappers = []any{}
	file_content_v1_rom_proto_msgTypes[4].OneofWrappers = []any{}
	file_content_v1_rom_proto_msgTypes[7].OneofWrappers = []any{
		(*RomUploadRequest_FileInfo)(nil),
		(*RomUploadRequest_ChunkData)(nil),
	}
	file_content_v1_rom_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_rom_proto_rawDesc), len(file_content_v1_rom_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_v1_rom_proto_goTypes,
		DependencyIndexes: file_content_v1_rom_proto_depIdxs,
		MessageInfos:      file_content_v1_rom_proto_msgTypes,
	}.Build()
	File_content_v1_rom_proto = out.File
	file_content_v1_rom_proto_goTypes = nil
	file_content_v1_rom_proto_depIdxs = nil
}
