// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: content/v1/romService.proto

package content

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_content_v1_romService_proto protoreflect.FileDescriptor

const file_content_v1_romService_proto_rawDesc = "" +
	"\n" +
	"\x1bcontent/v1/romService.proto\x12\n" +
	"content.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14content/v1/rom.proto2\xbe\x06\n" +
	"\n" +
	"RomService\x12k\n" +
	"\fListConsoles\x12\x1f.content.v1.ListConsolesRequest\x1a .content.v1.ListConsolesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/consoles\x12`\n" +
	"\aRomList\x12\x1a.content.v1.RomListRequest\x1a\x1b.content.v1.RomListResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/roms/list\x12j\n" +
	"\tRomUpload\x12\x1c.content.v1.RomUploadRequest\x1a\x1d.content.v1.RomUploadResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/roms/upload(\x01\x12W\n" +
	"\x06RomGet\x12\x19.content.v1.RomGetRequest\x1a\x17.content.v1.RomMetadata\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/roms/{id}\x12`\n" +
	"\tRomUpdate\x12\x1c.content.v1.RomUpdateRequest\x1a\x17.content.v1.RomMetadata\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/v1/roms/{id}\x12c\n" +
	"\tRomDelete\x12\x1c.content.v1.RomDeleteRequest\x1a\x1d.content.v1.RomDeleteResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/roms/{id}\x12j\n" +
	"\vRomDownload\x12\x1e.content.v1.RomDownloadRequest\x1a\x15.content.v1.FileChunk\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/roms/{id}/download0\x01\x12i\n" +
	"\bRomShare\x12\x1b.content.v1.RomShareRequest\x1a\x1c.content.v1.RomShareResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/roms/{id}/shareB7Z5github.com/AyuuSaxena/my-protos-go/content/v1;contentb\x06proto3"

var file_content_v1_romService_proto_goTypes = []any{
	(*ListConsolesRequest)(nil),  // 0: content.v1.ListConsolesRequest
	(*RomListRequest)(nil),       // 1: content.v1.RomListRequest
	(*RomUploadRequest)(nil),     // 2: content.v1.RomUploadRequest
	(*RomGetRequest)(nil),        // 3: content.v1.RomGetRequest
	(*RomUpdateRequest)(nil),     // 4: content.v1.RomUpdateRequest
	(*RomDeleteRequest)(nil),     // 5: content.v1.RomDeleteRequest
	(*RomDownloadRequest)(nil),   // 6: content.v1.RomDownloadRequest
	(*RomShareRequest)(nil),      // 7: content.v1.RomShareRequest
	(*ListConsolesResponse)(nil), // 8: content.v1.ListConsolesResponse
	(*RomListResponse)(nil),      // 9: content.v1.RomListResponse
	(*RomUploadResponse)(nil),    // 10: content.v1.RomUploadResponse
	(*RomMetadata)(nil),          // 11: content.v1.RomMetadata
	(*RomDeleteResponse)(nil),    // 12: content.v1.RomDeleteResponse
	(*FileChunk)(nil),            // 13: content.v1.FileChunk
	(*RomShareResponse)(nil),     // 14: content.v1.RomShareResponse
}
var file_content_v1_romService_proto_depIdxs = []int32{
	0,  // 0: content.v1.RomService.ListConsoles:input_type -> content.v1.ListConsolesRequest
	1,  // 1: content.v1.RomService.RomList:input_type -> content.v1.RomListRequest
	2,  // 2: content.v1.RomService.RomUpload:input_type -> content.v1.RomUploadRequest
	3,  // 3: content.v1.RomService.RomGet:input_type -> content.v1.RomGetRequest
	4,  // 4: content.v1.RomService.RomUpdate:input_type -> content.v1.RomUpdateRequest
	5,  // 5: content.v1.RomService.RomDelete:input_type -> content.v1.RomDeleteRequest
	6,  // 6: content.v1.RomService.RomDownload:input_type -> content.v1.RomDownloadRequest
	7,  // 7: content.v1.RomService.RomShare:input_type -> content.v1.RomShareRequest
	8,  // 8: content.v1.RomService.ListConsoles:output_type -> content.v1.ListConsolesResponse
	9,  // 9: content.v1.RomService.RomList:output_type -> content.v1.RomListResponse
	10, // 10: content.v1.RomService.RomUpload:output_type -> content.v1.RomUploadResponse
	11, // 11: content.v1.RomService.RomGet:output_type -> content.v1.RomMetadata
	11, // 12: content.v1.RomService.RomUpdate:output_type -> content.v1.RomMetadata
	12, // 13: content.v1.RomService.RomDelete:output_type -> content.v1.RomDeleteResponse
	13, // 14: content.v1.RomService.RomDownload:output_type -> content.v1.FileChunk
	14, // 15: content.v1.RomService.RomShare:output_type -> content.v1.RomShareResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_content_v1_romService_proto_init() }
func file_content_v1_romService_proto_init() {
	if File_content_v1_romService_proto != nil {
		return
	}
	file_content_v1_rom_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_romService_proto_rawDesc), len(file_content_v1_romService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_content_v1_romService_proto_goTypes,
		DependencyIndexes: file_content_v1_romService_proto_depIdxs,
	}.Build()
	File_content_v1_romService_proto = out.File
	file_content_v1_romService_proto_goTypes = nil
	file_content_v1_romService_proto_depIdxs = nil
}
