// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: content/v1/romService.proto

package content

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RomService_RomGet_FullMethodName       = "/content.v1.RomService/RomGet"
	RomService_RomDownload_FullMethodName  = "/content.v1.RomService/RomDownload"
	RomService_RomList_FullMethodName      = "/content.v1.RomService/RomList"
	RomService_RomUpload_FullMethodName    = "/content.v1.RomService/RomUpload"
	RomService_RomUpdate_FullMethodName    = "/content.v1.RomService/RomUpdate"
	RomService_RomDelete_FullMethodName    = "/content.v1.RomService/RomDelete"
	RomService_RomShare_FullMethodName     = "/content.v1.RomService/RomShare"
	RomService_ListConsoles_FullMethodName = "/content.v1.RomService/ListConsoles"
)

// RomServiceClient is the client API for RomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RomServiceClient interface {
	RomGet(ctx context.Context, in *RomGetRequest, opts ...grpc.CallOption) (*RomMetadata, error)
	RomDownload(ctx context.Context, in *RomDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	RomList(ctx context.Context, in *RomListRequest, opts ...grpc.CallOption) (*RomListResponse, error)
	RomUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RomUploadRequest, RomUploadResponse], error)
	RomUpdate(ctx context.Context, in *RomUpdateRequest, opts ...grpc.CallOption) (*RomMetadata, error)
	RomDelete(ctx context.Context, in *RomDeleteRequest, opts ...grpc.CallOption) (*RomDeleteResponse, error)
	RomShare(ctx context.Context, in *RomShareRequest, opts ...grpc.CallOption) (*RomShareResponse, error)
	ListConsoles(ctx context.Context, in *ListConsolesRequest, opts ...grpc.CallOption) (*ListConsolesResponse, error)
}

type romServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRomServiceClient(cc grpc.ClientConnInterface) RomServiceClient {
	return &romServiceClient{cc}
}

func (c *romServiceClient) RomGet(ctx context.Context, in *RomGetRequest, opts ...grpc.CallOption) (*RomMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RomMetadata)
	err := c.cc.Invoke(ctx, RomService_RomGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *romServiceClient) RomDownload(ctx context.Context, in *RomDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RomService_ServiceDesc.Streams[0], RomService_RomDownload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RomDownloadRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RomService_RomDownloadClient = grpc.ServerStreamingClient[FileChunk]

func (c *romServiceClient) RomList(ctx context.Context, in *RomListRequest, opts ...grpc.CallOption) (*RomListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RomListResponse)
	err := c.cc.Invoke(ctx, RomService_RomList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *romServiceClient) RomUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RomUploadRequest, RomUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RomService_ServiceDesc.Streams[1], RomService_RomUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RomUploadRequest, RomUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RomService_RomUploadClient = grpc.ClientStreamingClient[RomUploadRequest, RomUploadResponse]

func (c *romServiceClient) RomUpdate(ctx context.Context, in *RomUpdateRequest, opts ...grpc.CallOption) (*RomMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RomMetadata)
	err := c.cc.Invoke(ctx, RomService_RomUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *romServiceClient) RomDelete(ctx context.Context, in *RomDeleteRequest, opts ...grpc.CallOption) (*RomDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RomDeleteResponse)
	err := c.cc.Invoke(ctx, RomService_RomDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *romServiceClient) RomShare(ctx context.Context, in *RomShareRequest, opts ...grpc.CallOption) (*RomShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RomShareResponse)
	err := c.cc.Invoke(ctx, RomService_RomShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *romServiceClient) ListConsoles(ctx context.Context, in *ListConsolesRequest, opts ...grpc.CallOption) (*ListConsolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsolesResponse)
	err := c.cc.Invoke(ctx, RomService_ListConsoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RomServiceServer is the server API for RomService service.
// All implementations must embed UnimplementedRomServiceServer
// for forward compatibility.
type RomServiceServer interface {
	RomGet(context.Context, *RomGetRequest) (*RomMetadata, error)
	RomDownload(*RomDownloadRequest, grpc.ServerStreamingServer[FileChunk]) error
	RomList(context.Context, *RomListRequest) (*RomListResponse, error)
	RomUpload(grpc.ClientStreamingServer[RomUploadRequest, RomUploadResponse]) error
	RomUpdate(context.Context, *RomUpdateRequest) (*RomMetadata, error)
	RomDelete(context.Context, *RomDeleteRequest) (*RomDeleteResponse, error)
	RomShare(context.Context, *RomShareRequest) (*RomShareResponse, error)
	ListConsoles(context.Context, *ListConsolesRequest) (*ListConsolesResponse, error)
	mustEmbedUnimplementedRomServiceServer()
}

// UnimplementedRomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRomServiceServer struct{}

func (UnimplementedRomServiceServer) RomGet(context.Context, *RomGetRequest) (*RomMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method RomGet not implemented")
}
func (UnimplementedRomServiceServer) RomDownload(*RomDownloadRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method RomDownload not implemented")
}
func (UnimplementedRomServiceServer) RomList(context.Context, *RomListRequest) (*RomListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RomList not implemented")
}
func (UnimplementedRomServiceServer) RomUpload(grpc.ClientStreamingServer[RomUploadRequest, RomUploadResponse]) error {
	return status.Error(codes.Unimplemented, "method RomUpload not implemented")
}
func (UnimplementedRomServiceServer) RomUpdate(context.Context, *RomUpdateRequest) (*RomMetadata, error) {
	return nil, status.Error(codes.Unimplemented, "method RomUpdate not implemented")
}
func (UnimplementedRomServiceServer) RomDelete(context.Context, *RomDeleteRequest) (*RomDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RomDelete not implemented")
}
func (UnimplementedRomServiceServer) RomShare(context.Context, *RomShareRequest) (*RomShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RomShare not implemented")
}
func (UnimplementedRomServiceServer) ListConsoles(context.Context, *ListConsolesRequest) (*ListConsolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsoles not implemented")
}
func (UnimplementedRomServiceServer) mustEmbedUnimplementedRomServiceServer() {}
func (UnimplementedRomServiceServer) testEmbeddedByValue()                    {}

// UnsafeRomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RomServiceServer will
// result in compilation errors.
type UnsafeRomServiceServer interface {
	mustEmbedUnimplementedRomServiceServer()
}

func RegisterRomServiceServer(s grpc.ServiceRegistrar, srv RomServiceServer) {
	// If the following call panics, it indicates UnimplementedRomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RomService_ServiceDesc, srv)
}

func _RomService_RomGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RomGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RomServiceServer).RomGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RomService_RomGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RomServiceServer).RomGet(ctx, req.(*RomGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RomService_RomDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RomDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RomServiceServer).RomDownload(m, &grpc.GenericServerStream[RomDownloadRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RomService_RomDownloadServer = grpc.ServerStreamingServer[FileChunk]

func _RomService_RomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RomListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RomServiceServer).RomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RomService_RomList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RomServiceServer).RomList(ctx, req.(*RomListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RomService_RomUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RomServiceServer).RomUpload(&grpc.GenericServerStream[RomUploadRequest, RomUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RomService_RomUploadServer = grpc.ClientStreamingServer[RomUploadRequest, RomUploadResponse]

func _RomService_RomUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RomUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RomServiceServer).RomUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RomService_RomUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RomServiceServer).RomUpdate(ctx, req.(*RomUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RomService_RomDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RomDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RomServiceServer).RomDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RomService_RomDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RomServiceServer).RomDelete(ctx, req.(*RomDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RomService_RomShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RomShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RomServiceServer).RomShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RomService_RomShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RomServiceServer).RomShare(ctx, req.(*RomShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RomService_ListConsoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RomServiceServer).ListConsoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RomService_ListConsoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RomServiceServer).ListConsoles(ctx, req.(*ListConsolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RomService_ServiceDesc is the grpc.ServiceDesc for RomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "content.v1.RomService",
	HandlerType: (*RomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RomGet",
			Handler:    _RomService_RomGet_Handler,
		},
		{
			MethodName: "RomList",
			Handler:    _RomService_RomList_Handler,
		},
		{
			MethodName: "RomUpdate",
			Handler:    _RomService_RomUpdate_Handler,
		},
		{
			MethodName: "RomDelete",
			Handler:    _RomService_RomDelete_Handler,
		},
		{
			MethodName: "RomShare",
			Handler:    _RomService_RomShare_Handler,
		},
		{
			MethodName: "ListConsoles",
			Handler:    _RomService_ListConsoles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RomDownload",
			Handler:       _RomService_RomDownload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RomUpload",
			Handler:       _RomService_RomUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "content/v1/romService.proto",
}
