// Code generated by MockGen. DO NOT EDIT.
// Source: protos-go/identity/v1/service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=protos-go/identity/v1/service_grpc.pb.go -destination=protos-go/mocks/identity/v1/service_mock.go -package=identity_mock
//

// Package identity_mock is a generated GoMock package.
package identity_mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/AyuuSaxena/my-protos-go/identity/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIdentityServiceClient is a mock of IdentityServiceClient interface.
type MockIdentityServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceClientMockRecorder
	isgomock struct{}
}

// MockIdentityServiceClientMockRecorder is the mock recorder for MockIdentityServiceClient.
type MockIdentityServiceClientMockRecorder struct {
	mock *MockIdentityServiceClient
}

// NewMockIdentityServiceClient creates a new mock instance.
func NewMockIdentityServiceClient(ctrl *gomock.Controller) *MockIdentityServiceClient {
	mock := &MockIdentityServiceClient{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityServiceClient) EXPECT() *MockIdentityServiceClientMockRecorder {
	return m.recorder
}

// IdentityCreate mocks base method.
func (m *MockIdentityServiceClient) IdentityCreate(ctx context.Context, in *v1.IdentityCreateAccountRequest, opts ...grpc.CallOption) (*v1.IdentityCreateAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IdentityCreate", varargs...)
	ret0, _ := ret[0].(*v1.IdentityCreateAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityCreate indicates an expected call of IdentityCreate.
func (mr *MockIdentityServiceClientMockRecorder) IdentityCreate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityCreate", reflect.TypeOf((*MockIdentityServiceClient)(nil).IdentityCreate), varargs...)
}

// IdentityGet mocks base method.
func (m *MockIdentityServiceClient) IdentityGet(ctx context.Context, in *v1.IdentityGetRequest, opts ...grpc.CallOption) (*v1.Identity, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IdentityGet", varargs...)
	ret0, _ := ret[0].(*v1.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityGet indicates an expected call of IdentityGet.
func (mr *MockIdentityServiceClientMockRecorder) IdentityGet(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityGet", reflect.TypeOf((*MockIdentityServiceClient)(nil).IdentityGet), varargs...)
}

// IdentityLogin mocks base method.
func (m *MockIdentityServiceClient) IdentityLogin(ctx context.Context, in *v1.IdentityAuthRequest, opts ...grpc.CallOption) (*v1.IdentityAuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IdentityLogin", varargs...)
	ret0, _ := ret[0].(*v1.IdentityAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityLogin indicates an expected call of IdentityLogin.
func (mr *MockIdentityServiceClientMockRecorder) IdentityLogin(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityLogin", reflect.TypeOf((*MockIdentityServiceClient)(nil).IdentityLogin), varargs...)
}

// IdentityOtpValidate mocks base method.
func (m *MockIdentityServiceClient) IdentityOtpValidate(ctx context.Context, in *v1.IdentityOtpValidateRequest, opts ...grpc.CallOption) (*v1.IdentityAuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IdentityOtpValidate", varargs...)
	ret0, _ := ret[0].(*v1.IdentityAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityOtpValidate indicates an expected call of IdentityOtpValidate.
func (mr *MockIdentityServiceClientMockRecorder) IdentityOtpValidate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityOtpValidate", reflect.TypeOf((*MockIdentityServiceClient)(nil).IdentityOtpValidate), varargs...)
}

// IdentityRefershToken mocks base method.
func (m *MockIdentityServiceClient) IdentityRefershToken(ctx context.Context, in *v1.IdentityRefreshTokenRequest, opts ...grpc.CallOption) (*v1.IdentityAuthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IdentityRefershToken", varargs...)
	ret0, _ := ret[0].(*v1.IdentityAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityRefershToken indicates an expected call of IdentityRefershToken.
func (mr *MockIdentityServiceClientMockRecorder) IdentityRefershToken(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityRefershToken", reflect.TypeOf((*MockIdentityServiceClient)(nil).IdentityRefershToken), varargs...)
}

// IdentityUpdate mocks base method.
func (m *MockIdentityServiceClient) IdentityUpdate(ctx context.Context, in *v1.IdentityUpdateRequest, opts ...grpc.CallOption) (*v1.Identity, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IdentityUpdate", varargs...)
	ret0, _ := ret[0].(*v1.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityUpdate indicates an expected call of IdentityUpdate.
func (mr *MockIdentityServiceClientMockRecorder) IdentityUpdate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityUpdate", reflect.TypeOf((*MockIdentityServiceClient)(nil).IdentityUpdate), varargs...)
}

// MockIdentityServiceServer is a mock of IdentityServiceServer interface.
type MockIdentityServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityServiceServerMockRecorder
	isgomock struct{}
}

// MockIdentityServiceServerMockRecorder is the mock recorder for MockIdentityServiceServer.
type MockIdentityServiceServerMockRecorder struct {
	mock *MockIdentityServiceServer
}

// NewMockIdentityServiceServer creates a new mock instance.
func NewMockIdentityServiceServer(ctrl *gomock.Controller) *MockIdentityServiceServer {
	mock := &MockIdentityServiceServer{ctrl: ctrl}
	mock.recorder = &MockIdentityServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityServiceServer) EXPECT() *MockIdentityServiceServerMockRecorder {
	return m.recorder
}

// IdentityCreate mocks base method.
func (m *MockIdentityServiceServer) IdentityCreate(arg0 context.Context, arg1 *v1.IdentityCreateAccountRequest) (*v1.IdentityCreateAccountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityCreate", arg0, arg1)
	ret0, _ := ret[0].(*v1.IdentityCreateAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityCreate indicates an expected call of IdentityCreate.
func (mr *MockIdentityServiceServerMockRecorder) IdentityCreate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityCreate", reflect.TypeOf((*MockIdentityServiceServer)(nil).IdentityCreate), arg0, arg1)
}

// IdentityGet mocks base method.
func (m *MockIdentityServiceServer) IdentityGet(arg0 context.Context, arg1 *v1.IdentityGetRequest) (*v1.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityGet", arg0, arg1)
	ret0, _ := ret[0].(*v1.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityGet indicates an expected call of IdentityGet.
func (mr *MockIdentityServiceServerMockRecorder) IdentityGet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityGet", reflect.TypeOf((*MockIdentityServiceServer)(nil).IdentityGet), arg0, arg1)
}

// IdentityLogin mocks base method.
func (m *MockIdentityServiceServer) IdentityLogin(arg0 context.Context, arg1 *v1.IdentityAuthRequest) (*v1.IdentityAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityLogin", arg0, arg1)
	ret0, _ := ret[0].(*v1.IdentityAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityLogin indicates an expected call of IdentityLogin.
func (mr *MockIdentityServiceServerMockRecorder) IdentityLogin(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityLogin", reflect.TypeOf((*MockIdentityServiceServer)(nil).IdentityLogin), arg0, arg1)
}

// IdentityOtpValidate mocks base method.
func (m *MockIdentityServiceServer) IdentityOtpValidate(arg0 context.Context, arg1 *v1.IdentityOtpValidateRequest) (*v1.IdentityAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityOtpValidate", arg0, arg1)
	ret0, _ := ret[0].(*v1.IdentityAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityOtpValidate indicates an expected call of IdentityOtpValidate.
func (mr *MockIdentityServiceServerMockRecorder) IdentityOtpValidate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityOtpValidate", reflect.TypeOf((*MockIdentityServiceServer)(nil).IdentityOtpValidate), arg0, arg1)
}

// IdentityRefershToken mocks base method.
func (m *MockIdentityServiceServer) IdentityRefershToken(arg0 context.Context, arg1 *v1.IdentityRefreshTokenRequest) (*v1.IdentityAuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityRefershToken", arg0, arg1)
	ret0, _ := ret[0].(*v1.IdentityAuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityRefershToken indicates an expected call of IdentityRefershToken.
func (mr *MockIdentityServiceServerMockRecorder) IdentityRefershToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityRefershToken", reflect.TypeOf((*MockIdentityServiceServer)(nil).IdentityRefershToken), arg0, arg1)
}

// IdentityUpdate mocks base method.
func (m *MockIdentityServiceServer) IdentityUpdate(arg0 context.Context, arg1 *v1.IdentityUpdateRequest) (*v1.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IdentityUpdate", arg0, arg1)
	ret0, _ := ret[0].(*v1.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IdentityUpdate indicates an expected call of IdentityUpdate.
func (mr *MockIdentityServiceServerMockRecorder) IdentityUpdate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IdentityUpdate", reflect.TypeOf((*MockIdentityServiceServer)(nil).IdentityUpdate), arg0, arg1)
}

// mustEmbedUnimplementedIdentityServiceServer mocks base method.
func (m *MockIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedIdentityServiceServer")
}

// mustEmbedUnimplementedIdentityServiceServer indicates an expected call of mustEmbedUnimplementedIdentityServiceServer.
func (mr *MockIdentityServiceServerMockRecorder) mustEmbedUnimplementedIdentityServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedIdentityServiceServer", reflect.TypeOf((*MockIdentityServiceServer)(nil).mustEmbedUnimplementedIdentityServiceServer))
}

// MockUnsafeIdentityServiceServer is a mock of UnsafeIdentityServiceServer interface.
type MockUnsafeIdentityServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeIdentityServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeIdentityServiceServerMockRecorder is the mock recorder for MockUnsafeIdentityServiceServer.
type MockUnsafeIdentityServiceServerMockRecorder struct {
	mock *MockUnsafeIdentityServiceServer
}

// NewMockUnsafeIdentityServiceServer creates a new mock instance.
func NewMockUnsafeIdentityServiceServer(ctrl *gomock.Controller) *MockUnsafeIdentityServiceServer {
	mock := &MockUnsafeIdentityServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeIdentityServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeIdentityServiceServer) EXPECT() *MockUnsafeIdentityServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedIdentityServiceServer mocks base method.
func (m *MockUnsafeIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedIdentityServiceServer")
}

// mustEmbedUnimplementedIdentityServiceServer indicates an expected call of mustEmbedUnimplementedIdentityServiceServer.
func (mr *MockUnsafeIdentityServiceServerMockRecorder) mustEmbedUnimplementedIdentityServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedIdentityServiceServer", reflect.TypeOf((*MockUnsafeIdentityServiceServer)(nil).mustEmbedUnimplementedIdentityServiceServer))
}
