// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: content/v1/image/image.proto

package image

import (
	v1 "github.com/AyuuSaxena/protos-go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ImageMetadata represents the core normalized Image entity with relational IDs.
type ImageMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MongoDB internal record identifier (_id)
	// @gotags: `json:"mongoId,omitempty" bson:"_id,omitempty"`
	MongoId string `protobuf:"bytes,1,opt,name=mongo_id,json=mongoId,proto3" json:"mongoId,omitempty" bson:"_id,omitempty"`
	// Unique Image identifier (UUID)
	// @gotags: `json:"id,omitempty" bson:"id,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty" bson:"id,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site string `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	// Display title of the Image
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// URL-friendly slug
	Slug string `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	// Detailed description
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Relational Foreign Key to storage file
	// @gotags: `json:"fileId,omitempty" bson:"fileId,omitempty"`
	FileId string `protobuf:"bytes,7,opt,name=file_id,json=fileId,proto3" json:"fileId,omitempty" bson:"fileId,omitempty"`
	// Domain & Visual Metadata
	// @gotags: `json:"altText,omitempty" bson:"altText,omitempty"`
	AltText string `protobuf:"bytes,8,opt,name=alt_text,json=altText,proto3" json:"altText,omitempty" bson:"altText,omitempty"`
	// @gotags: `json:"width,omitempty" bson:"width,omitempty"`
	Width int32 `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty" bson:"width,omitempty"`
	// @gotags: `json:"height,omitempty" bson:"height,omitempty"`
	Height int32 `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty" bson:"height,omitempty"`
	// @gotags: `json:"aspectRatio,omitempty" bson:"aspectRatio,omitempty"`
	AspectRatio string `protobuf:"bytes,11,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspectRatio,omitempty" bson:"aspectRatio,omitempty"`
	// @gotags: `json:"format,omitempty" bson:"format,omitempty"`
	Format string `protobuf:"bytes,12,opt,name=format,proto3" json:"format,omitempty" bson:"format,omitempty"`
	// @gotags: `json:"category,omitempty" bson:"category,omitempty"`
	Category string   `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty" bson:"category,omitempty"`
	Tags     []string `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool `protobuf:"varint,15,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Lifecycle status (active, archived, draft)
	Status string `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,17,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// @gotags: `json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	UploaderUsername string `protobuf:"bytes,18,opt,name=uploader_username,json=uploaderUsername,proto3" json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	// @gotags: `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	CreatedAt string `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"createdAt,omitempty" bson:"createdAt,omitempty"`
	// @gotags: `json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	UpdatedAt string `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt,omitempty" bson:"updatedAt,omitempty"`
	// Enriched Relations (populated on read, not persisted in DB)
	// Full file details resolved from fileId
	// @gotags: `json:"fileMetadata,omitempty" bson:"fileMetadata,omitempty"`
	FileMetadata  *v1.FileMetadata `protobuf:"bytes,21,opt,name=file_metadata,json=fileMetadata,proto3" json:"fileMetadata,omitempty" bson:"fileMetadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMetadata) Reset() {
	*x = ImageMetadata{}
	mi := &file_content_v1_image_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMetadata) ProtoMessage() {}

func (x *ImageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMetadata.ProtoReflect.Descriptor instead.
func (*ImageMetadata) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImageMetadata) GetMongoId() string {
	if x != nil {
		return x.MongoId
	}
	return ""
}

func (x *ImageMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageMetadata) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *ImageMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImageMetadata) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ImageMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImageMetadata) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ImageMetadata) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *ImageMetadata) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageMetadata) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageMetadata) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *ImageMetadata) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImageMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ImageMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ImageMetadata) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ImageMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImageMetadata) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *ImageMetadata) GetUploaderUsername() string {
	if x != nil {
		return x.UploaderUsername
	}
	return ""
}

func (x *ImageMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ImageMetadata) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ImageMetadata) GetFileMetadata() *v1.FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

type ImageGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image unique identifier
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Image name to match
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Image URL slug
	Slug *string `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,4,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageGetRequest) Reset() {
	*x = ImageGetRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGetRequest) ProtoMessage() {}

func (x *ImageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGetRequest.ProtoReflect.Descriptor instead.
func (*ImageGetRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageGetRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ImageGetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ImageGetRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *ImageGetRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageDownloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image unique identifier
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Image name to match
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Image URL slug
	Slug *string `protobuf:"bytes,3,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,4,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDownloadRequest) Reset() {
	*x = ImageDownloadRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDownloadRequest) ProtoMessage() {}

func (x *ImageDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDownloadRequest.ProtoReflect.Descriptor instead.
func (*ImageDownloadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{2}
}

func (x *ImageDownloadRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ImageDownloadRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ImageDownloadRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *ImageDownloadRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by Image name (partial or exact)
	// @gotags: `form:"name" json:"name,omitempty" bson:"name,omitempty"`
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty" form:"name" bson:"name,omitempty"`
	// Filter by category (e.g. cover, screenshot, wallpaper)
	// @gotags: `form:"category" json:"category,omitempty" bson:"category,omitempty"`
	Category *string `protobuf:"bytes,2,opt,name=category,proto3,oneof" json:"category,omitempty" form:"category" bson:"category,omitempty"`
	// Filter by format (e.g. png, jpeg, webp)
	// @gotags: `form:"format" json:"format,omitempty" bson:"format,omitempty"`
	Format *string `protobuf:"bytes,3,opt,name=format,proto3,oneof" json:"format,omitempty" form:"format" bson:"format,omitempty"`
	// Filter by content status (e.g. active, archived)
	// @gotags: `form:"status" json:"status,omitempty" bson:"status,omitempty"`
	Status *string `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty" form:"status" bson:"status,omitempty"`
	// Filter by public visibility
	// @gotags: `form:"isPublic" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic *bool `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" form:"isPublic" bson:"isPublic,omitempty"`
	// Filter by tag
	// @gotags: `form:"tag" json:"tag,omitempty" bson:"tag,omitempty"`
	Tag *string `protobuf:"bytes,6,opt,name=tag,proto3,oneof" json:"tag,omitempty" form:"tag" bson:"tag,omitempty"`
	// Filter by uploader user ID
	// @gotags: `form:"uploaderId" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId *string `protobuf:"bytes,7,opt,name=uploader_id,json=uploaderId,proto3,oneof" json:"uploaderId,omitempty" form:"uploaderId" bson:"uploaderId,omitempty"`
	// Filter by site key (e.g. retrogames)
	// @gotags: `form:"site" json:"site,omitempty" bson:"site,omitempty"`
	Site          *string `protobuf:"bytes,8,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site" bson:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageQuery) Reset() {
	*x = ImageQuery{}
	mi := &file_content_v1_image_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageQuery) ProtoMessage() {}

func (x *ImageQuery) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageQuery.ProtoReflect.Descriptor instead.
func (*ImageQuery) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{3}
}

func (x *ImageQuery) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ImageQuery) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ImageQuery) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *ImageQuery) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ImageQuery) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *ImageQuery) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *ImageQuery) GetUploaderId() string {
	if x != nil && x.UploaderId != nil {
		return *x.UploaderId
	}
	return ""
}

func (x *ImageQuery) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageSearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of items to return (default 20, max 100)
	// @gotags: `form:"limit" json:"limit,omitempty" bson:"limit,omitempty"`
	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty" form:"limit" bson:"limit,omitempty"`
	// Number of items to skip for pagination (default 0)
	// @gotags: `form:"offset" json:"offset,omitempty" bson:"offset,omitempty"`
	Offset *int32 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty" form:"offset" bson:"offset,omitempty"`
	// Keyword search across title, description, and tags
	// @gotags: `form:"keyword" json:"keyword,omitempty" bson:"keyword,omitempty"`
	Keyword *string `protobuf:"bytes,3,opt,name=keyword,proto3,oneof" json:"keyword,omitempty" form:"keyword" bson:"keyword,omitempty"`
	// Field name to sort by (e.g. title, createdAt)
	// @gotags: `form:"sortby" json:"sortby,omitempty" bson:"sortby,omitempty"`
	Sortby *string `protobuf:"bytes,4,opt,name=sortby,proto3,oneof" json:"sortby,omitempty" form:"sortby" bson:"sortby,omitempty"`
	// Sort direction order (asc or desc, default desc)
	// @gotags: `form:"sortOrder" json:"sortOrder,omitempty" bson:"sortOrder,omitempty"`
	SortOrder *string `protobuf:"bytes,5,opt,name=sort_order,json=sortOrder,proto3,oneof" json:"sortOrder,omitempty" form:"sortOrder" bson:"sortOrder,omitempty"`
	// Nested query filters for Image properties
	// @gotags: `json:"query,omitempty" bson:"query,omitempty"`
	Query *ImageQuery `protobuf:"bytes,6,opt,name=query,proto3,oneof" json:"query,omitempty" bson:"query,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty" bson:"site,omitempty"`
	Site          *string `protobuf:"bytes,7,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site" bson:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSearchRequest) Reset() {
	*x = ImageSearchRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchRequest) ProtoMessage() {}

func (x *ImageSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchRequest.ProtoReflect.Descriptor instead.
func (*ImageSearchRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{4}
}

func (x *ImageSearchRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ImageSearchRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ImageSearchRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

func (x *ImageSearchRequest) GetSortby() string {
	if x != nil && x.Sortby != nil {
		return *x.Sortby
	}
	return ""
}

func (x *ImageSearchRequest) GetSortOrder() string {
	if x != nil && x.SortOrder != nil {
		return *x.SortOrder
	}
	return ""
}

func (x *ImageSearchRequest) GetQuery() *ImageQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ImageSearchRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageSearchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of Image metadata items for the current page
	Images []*ImageMetadata `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	// Total count of items matching the query
	// @gotags: `json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	TotalCount int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty" bson:"totalCount,omitempty"`
	// Page size limit applied
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset applied
	Offset int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	// Calculated total number of pages
	// @gotags: `json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	TotalPages    int32 `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"totalPages,omitempty" bson:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSearchResponse) Reset() {
	*x = ImageSearchResponse{}
	mi := &file_content_v1_image_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSearchResponse) ProtoMessage() {}

func (x *ImageSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSearchResponse.ProtoReflect.Descriptor instead.
func (*ImageSearchResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{5}
}

func (x *ImageSearchResponse) GetImages() []*ImageMetadata {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ImageSearchResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ImageSearchResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ImageSearchResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ImageSearchResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type ImageFileInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MIME type
	// @gotags: `json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mimeType,omitempty" bson:"mimeType,omitempty"`
	// File size in bytes
	// @gotags: `json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	SizeBytes int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"sizeBytes,omitempty" bson:"sizeBytes,omitempty"`
	// Image title
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// Image description
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Alt text
	// @gotags: `json:"altText,omitempty" bson:"altText,omitempty"`
	AltText string `protobuf:"bytes,6,opt,name=alt_text,json=altText,proto3" json:"altText,omitempty" bson:"altText,omitempty"`
	// Category (e.g. cover, screenshot, wallpaper)
	Category string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	// Category tags
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// Public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic bool `protobuf:"varint,9,opt,name=is_public,json=isPublic,proto3" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Custom storage key if specified
	// @gotags: `json:"customKey,omitempty" bson:"customKey,omitempty"`
	CustomKey string `protobuf:"bytes,10,opt,name=custom_key,json=customKey,proto3" json:"customKey,omitempty" bson:"customKey,omitempty"`
	// Uploader user ID
	// @gotags: `json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	UploaderId string `protobuf:"bytes,11,opt,name=uploader_id,json=uploaderId,proto3" json:"uploaderId,omitempty" bson:"uploaderId,omitempty"`
	// Uploader username
	// @gotags: `json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	UploaderUsername string `protobuf:"bytes,12,opt,name=uploader_username,json=uploaderUsername,proto3" json:"uploaderUsername,omitempty" bson:"uploaderUsername,omitempty"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site          string `protobuf:"bytes,13,opt,name=site,proto3" json:"site,omitempty" bson:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageFileInfo) Reset() {
	*x = ImageFileInfo{}
	mi := &file_content_v1_image_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageFileInfo) ProtoMessage() {}

func (x *ImageFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageFileInfo.ProtoReflect.Descriptor instead.
func (*ImageFileInfo) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{6}
}

func (x *ImageFileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageFileInfo) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ImageFileInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImageFileInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ImageFileInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImageFileInfo) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *ImageFileInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ImageFileInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ImageFileInfo) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *ImageFileInfo) GetCustomKey() string {
	if x != nil {
		return x.CustomKey
	}
	return ""
}

func (x *ImageFileInfo) GetUploaderId() string {
	if x != nil {
		return x.UploaderId
	}
	return ""
}

func (x *ImageFileInfo) GetUploaderUsername() string {
	if x != nil {
		return x.UploaderUsername
	}
	return ""
}

func (x *ImageFileInfo) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image display title
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Image description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Alt text
	// @gotags: `json:"altText,omitempty" bson:"altText,omitempty" form:"altText"`
	AltText string `protobuf:"bytes,3,opt,name=alt_text,json=altText,proto3" json:"altText,omitempty" bson:"altText,omitempty" form:"altText"`
	// Category (e.g. cover, screenshot, wallpaper)
	// @gotags: `json:"category,omitempty" bson:"category,omitempty" form:"category"`
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty" bson:"category,omitempty" form:"category"`
	// Category tags
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty" form:"isPublic"`
	IsPublic *bool `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" bson:"isPublic,omitempty" form:"isPublic"`
	// Custom storage key
	// @gotags: `json:"customKey,omitempty" bson:"customKey,omitempty" form:"customKey"`
	CustomKey string `protobuf:"bytes,7,opt,name=custom_key,json=customKey,proto3" json:"customKey,omitempty" bson:"customKey,omitempty" form:"customKey"`
	// Dynamic site/tenant key (e.g. retrogames)
	// @gotags: `json:"site,omitempty" bson:"site,omitempty" form:"site"`
	Site          *string `protobuf:"bytes,8,opt,name=site,proto3,oneof" json:"site,omitempty" bson:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{7}
}

func (x *UploadImageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UploadImageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UploadImageRequest) GetAltText() string {
	if x != nil {
		return x.AltText
	}
	return ""
}

func (x *UploadImageRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UploadImageRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UploadImageRequest) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *UploadImageRequest) GetCustomKey() string {
	if x != nil {
		return x.CustomKey
	}
	return ""
}

func (x *UploadImageRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestData:
	//
	//	*ImageUploadRequest_FileInfo
	//	*ImageUploadRequest_ChunkData
	RequestData   isImageUploadRequest_RequestData `protobuf_oneof:"request_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUploadRequest) Reset() {
	*x = ImageUploadRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadRequest) ProtoMessage() {}

func (x *ImageUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadRequest.ProtoReflect.Descriptor instead.
func (*ImageUploadRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{8}
}

func (x *ImageUploadRequest) GetRequestData() isImageUploadRequest_RequestData {
	if x != nil {
		return x.RequestData
	}
	return nil
}

func (x *ImageUploadRequest) GetFileInfo() *ImageFileInfo {
	if x != nil {
		if x, ok := x.RequestData.(*ImageUploadRequest_FileInfo); ok {
			return x.FileInfo
		}
	}
	return nil
}

func (x *ImageUploadRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.RequestData.(*ImageUploadRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isImageUploadRequest_RequestData interface {
	isImageUploadRequest_RequestData()
}

type ImageUploadRequest_FileInfo struct {
	// Image metadata for initial chunk
	// @gotags: `json:"fileInfo,omitempty" bson:"fileInfo,omitempty"`
	FileInfo *ImageFileInfo `protobuf:"bytes,1,opt,name=file_info,json=fileInfo,proto3,oneof" json:"fileInfo,omitempty" bson:"fileInfo,omitempty"`
}

type ImageUploadRequest_ChunkData struct {
	// Binary chunk data
	// @gotags: `json:"chunkData,omitempty" bson:"chunkData,omitempty"`
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof" json:"chunkData,omitempty" bson:"chunkData,omitempty"`
}

func (*ImageUploadRequest_FileInfo) isImageUploadRequest_RequestData() {}

func (*ImageUploadRequest_ChunkData) isImageUploadRequest_RequestData() {}

type ImageUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uploaded Image metadata
	Image         *ImageMetadata `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUploadResponse) Reset() {
	*x = ImageUploadResponse{}
	mi := &file_content_v1_image_image_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUploadResponse) ProtoMessage() {}

func (x *ImageUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUploadResponse.ProtoReflect.Descriptor instead.
func (*ImageUploadResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{9}
}

func (x *ImageUploadResponse) GetImage() *ImageMetadata {
	if x != nil {
		return x.Image
	}
	return nil
}

type ImageUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Image identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Updated Image title
	Title *string `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// Updated Image description
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Updated alt text
	// @gotags: `json:"altText,omitempty" bson:"altText,omitempty"`
	AltText *string `protobuf:"bytes,4,opt,name=alt_text,json=altText,proto3,oneof" json:"altText,omitempty" bson:"altText,omitempty"`
	// Updated category
	// @gotags: `json:"category,omitempty" bson:"category,omitempty"`
	Category *string `protobuf:"bytes,5,opt,name=category,proto3,oneof" json:"category,omitempty" bson:"category,omitempty"`
	// Updated tags
	Tags []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	// Updated public visibility flag
	// @gotags: `json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	IsPublic *bool `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3,oneof" json:"isPublic,omitempty" bson:"isPublic,omitempty"`
	// Updated lifecycle status
	// @gotags: `json:"status,omitempty" bson:"status,omitempty"`
	Status *string `protobuf:"bytes,8,opt,name=status,proto3,oneof" json:"status,omitempty" bson:"status,omitempty"`
	// Updated site identifier
	// @gotags: `json:"site,omitempty" bson:"site,omitempty"`
	Site          *string `protobuf:"bytes,9,opt,name=site,proto3,oneof" json:"site,omitempty" bson:"site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageUpdateRequest) Reset() {
	*x = ImageUpdateRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageUpdateRequest) ProtoMessage() {}

func (x *ImageUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageUpdateRequest.ProtoReflect.Descriptor instead.
func (*ImageUpdateRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{10}
}

func (x *ImageUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageUpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ImageUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ImageUpdateRequest) GetAltText() string {
	if x != nil && x.AltText != nil {
		return *x.AltText
	}
	return ""
}

func (x *ImageUpdateRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ImageUpdateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ImageUpdateRequest) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *ImageUpdateRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ImageUpdateRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Image identifier to delete
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Hard delete flag (permanently remove file from storage and database)
	// @gotags: `json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	HardDelete bool `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hardDelete,omitempty" bson:"hardDelete,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,3,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDeleteRequest) Reset() {
	*x = ImageDeleteRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDeleteRequest) ProtoMessage() {}

func (x *ImageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDeleteRequest.ProtoReflect.Descriptor instead.
func (*ImageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{11}
}

func (x *ImageDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageDeleteRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

func (x *ImageDeleteRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation success flag
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Status message
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageDeleteResponse) Reset() {
	*x = ImageDeleteResponse{}
	mi := &file_content_v1_image_image_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageDeleteResponse) ProtoMessage() {}

func (x *ImageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageDeleteResponse.ProtoReflect.Descriptor instead.
func (*ImageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{12}
}

func (x *ImageDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImageDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImageShareRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique Image identifier to share
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Pre-signed download URL expiration duration in seconds
	// @gotags: `json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	ExpiresInSec int32 `protobuf:"varint,2,opt,name=expires_in_sec,json=expiresInSec,proto3" json:"expiresInSec,omitempty" bson:"expiresInSec,omitempty"`
	// Optional site identifier
	// @gotags: `form:"site" json:"site,omitempty"`
	Site          *string `protobuf:"bytes,3,opt,name=site,proto3,oneof" json:"site,omitempty" form:"site"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageShareRequest) Reset() {
	*x = ImageShareRequest{}
	mi := &file_content_v1_image_image_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageShareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageShareRequest) ProtoMessage() {}

func (x *ImageShareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageShareRequest.ProtoReflect.Descriptor instead.
func (*ImageShareRequest) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{13}
}

func (x *ImageShareRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageShareRequest) GetExpiresInSec() int32 {
	if x != nil {
		return x.ExpiresInSec
	}
	return 0
}

func (x *ImageShareRequest) GetSite() string {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return ""
}

type ImageShareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Generated pre-signed download URL
	// @gotags: `json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	DownloadUrl string `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"downloadUrl,omitempty" bson:"downloadUrl,omitempty"`
	// ISO-8601 expiration timestamp
	// @gotags: `json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	ExpiresAt     string `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expiresAt,omitempty" bson:"expiresAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageShareResponse) Reset() {
	*x = ImageShareResponse{}
	mi := &file_content_v1_image_image_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageShareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageShareResponse) ProtoMessage() {}

func (x *ImageShareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_content_v1_image_image_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageShareResponse.ProtoReflect.Descriptor instead.
func (*ImageShareResponse) Descriptor() ([]byte, []int) {
	return file_content_v1_image_image_proto_rawDescGZIP(), []int{14}
}

func (x *ImageShareResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageShareResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ImageShareResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_content_v1_image_image_proto protoreflect.FileDescriptor

const file_content_v1_image_image_proto_rawDesc = "" +
	"\n" +
	"\x1ccontent/v1/image/image.proto\x12\x10content.v1.image\x1a\x16common/v1/common.proto\"\xe6\x04\n" +
	"\rImageMetadata\x12\x19\n" +
	"\bmongo_id\x18\x01 \x01(\tR\amongoId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x03 \x01(\tR\x04site\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x17\n" +
	"\afile_id\x18\a \x01(\tR\x06fileId\x12\x19\n" +
	"\balt_text\x18\b \x01(\tR\aaltText\x12\x14\n" +
	"\x05width\x18\t \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\x05R\x06height\x12!\n" +
	"\faspect_ratio\x18\v \x01(\tR\vaspectRatio\x12\x16\n" +
	"\x06format\x18\f \x01(\tR\x06format\x12\x1a\n" +
	"\bcategory\x18\r \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x0f \x01(\bR\bisPublic\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12\x1f\n" +
	"\vuploader_id\x18\x11 \x01(\tR\n" +
	"uploaderId\x12+\n" +
	"\x11uploader_username\x18\x12 \x01(\tR\x10uploaderUsername\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\tR\tupdatedAt\x12<\n" +
	"\rfile_metadata\x18\x15 \x01(\v2\x17.common.v1.FileMetadataR\ffileMetadata\"\x93\x01\n" +
	"\x0fImageGetRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x02R\x04slug\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x04 \x01(\tH\x03R\x04site\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slugB\a\n" +
	"\x05_site\"\x98\x01\n" +
	"\x14ImageDownloadRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04slug\x18\x03 \x01(\tH\x02R\x04slug\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\x04 \x01(\tH\x03R\x04site\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_slugB\a\n" +
	"\x05_site\"\xd3\x02\n" +
	"\n" +
	"ImageQuery\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x02 \x01(\tH\x01R\bcategory\x88\x01\x01\x12\x1b\n" +
	"\x06format\x18\x03 \x01(\tH\x02R\x06format\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x03R\x06status\x88\x01\x01\x12 \n" +
	"\tis_public\x18\x05 \x01(\bH\x04R\bisPublic\x88\x01\x01\x12\x15\n" +
	"\x03tag\x18\x06 \x01(\tH\x05R\x03tag\x88\x01\x01\x12$\n" +
	"\vuploader_id\x18\a \x01(\tH\x06R\n" +
	"uploaderId\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\b \x01(\tH\aR\x04site\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_categoryB\t\n" +
	"\a_formatB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_is_publicB\x06\n" +
	"\x04_tagB\x0e\n" +
	"\f_uploader_idB\a\n" +
	"\x05_site\"\xcc\x02\n" +
	"\x12ImageSearchRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x05H\x01R\x06offset\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x03 \x01(\tH\x02R\akeyword\x88\x01\x01\x12\x1b\n" +
	"\x06sortby\x18\x04 \x01(\tH\x03R\x06sortby\x88\x01\x01\x12\"\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\tH\x04R\tsortOrder\x88\x01\x01\x127\n" +
	"\x05query\x18\x06 \x01(\v2\x1c.content.v1.image.ImageQueryH\x05R\x05query\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\a \x01(\tH\x06R\x04site\x88\x01\x01B\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\n" +
	"\n" +
	"\b_keywordB\t\n" +
	"\a_sortbyB\r\n" +
	"\v_sort_orderB\b\n" +
	"\x06_queryB\a\n" +
	"\x05_site\"\xbe\x01\n" +
	"\x13ImageSearchResponse\x127\n" +
	"\x06images\x18\x01 \x03(\v2\x1f.content.v1.image.ImageMetadataR\x06images\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\x80\x03\n" +
	"\rImageFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\balt_text\x18\x06 \x01(\tR\aaltText\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\t \x01(\bR\bisPublic\x12\x1d\n" +
	"\n" +
	"custom_key\x18\n" +
	" \x01(\tR\tcustomKey\x12\x1f\n" +
	"\vuploader_id\x18\v \x01(\tR\n" +
	"uploaderId\x12+\n" +
	"\x11uploader_username\x18\f \x01(\tR\x10uploaderUsername\x12\x12\n" +
	"\x04site\x18\r \x01(\tR\x04site\"\x88\x02\n" +
	"\x12UploadImageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\balt_text\x18\x03 \x01(\tR\aaltText\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12 \n" +
	"\tis_public\x18\x06 \x01(\bH\x00R\bisPublic\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"custom_key\x18\a \x01(\tR\tcustomKey\x12\x17\n" +
	"\x04site\x18\b \x01(\tH\x01R\x04site\x88\x01\x01B\f\n" +
	"\n" +
	"_is_publicB\a\n" +
	"\x05_site\"\x85\x01\n" +
	"\x12ImageUploadRequest\x12>\n" +
	"\tfile_info\x18\x01 \x01(\v2\x1f.content.v1.image.ImageFileInfoH\x00R\bfileInfo\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x0e\n" +
	"\frequest_data\"L\n" +
	"\x13ImageUploadResponse\x125\n" +
	"\x05image\x18\x01 \x01(\v2\x1f.content.v1.image.ImageMetadataR\x05image\"\xe9\x02\n" +
	"\x12ImageUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\balt_text\x18\x04 \x01(\tH\x02R\aaltText\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x05 \x01(\tH\x03R\bcategory\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12 \n" +
	"\tis_public\x18\a \x01(\bH\x04R\bisPublic\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\b \x01(\tH\x05R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04site\x18\t \x01(\tH\x06R\x04site\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_alt_textB\v\n" +
	"\t_categoryB\f\n" +
	"\n" +
	"_is_publicB\t\n" +
	"\a_statusB\a\n" +
	"\x05_site\"g\n" +
	"\x12ImageDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\x12\x17\n" +
	"\x04site\x18\x03 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_site\"I\n" +
	"\x13ImageDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\x11ImageShareRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0eexpires_in_sec\x18\x02 \x01(\x05R\fexpiresInSec\x12\x17\n" +
	"\x04site\x18\x03 \x01(\tH\x00R\x04site\x88\x01\x01B\a\n" +
	"\x05_site\"f\n" +
	"\x12ImageShareResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdownload_url\x18\x02 \x01(\tR\vdownloadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAtB8Z6github.com/AyuuSaxena/protos-go/content/v1/image;imageb\x06proto3"

var (
	file_content_v1_image_image_proto_rawDescOnce sync.Once
	file_content_v1_image_image_proto_rawDescData []byte
)

func file_content_v1_image_image_proto_rawDescGZIP() []byte {
	file_content_v1_image_image_proto_rawDescOnce.Do(func() {
		file_content_v1_image_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_v1_image_image_proto_rawDesc), len(file_content_v1_image_image_proto_rawDesc)))
	})
	return file_content_v1_image_image_proto_rawDescData
}

var file_content_v1_image_image_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_content_v1_image_image_proto_goTypes = []any{
	(*ImageMetadata)(nil),        // 0: content.v1.image.ImageMetadata
	(*ImageGetRequest)(nil),      // 1: content.v1.image.ImageGetRequest
	(*ImageDownloadRequest)(nil), // 2: content.v1.image.ImageDownloadRequest
	(*ImageQuery)(nil),           // 3: content.v1.image.ImageQuery
	(*ImageSearchRequest)(nil),   // 4: content.v1.image.ImageSearchRequest
	(*ImageSearchResponse)(nil),  // 5: content.v1.image.ImageSearchResponse
	(*ImageFileInfo)(nil),        // 6: content.v1.image.ImageFileInfo
	(*UploadImageRequest)(nil),   // 7: content.v1.image.UploadImageRequest
	(*ImageUploadRequest)(nil),   // 8: content.v1.image.ImageUploadRequest
	(*ImageUploadResponse)(nil),  // 9: content.v1.image.ImageUploadResponse
	(*ImageUpdateRequest)(nil),   // 10: content.v1.image.ImageUpdateRequest
	(*ImageDeleteRequest)(nil),   // 11: content.v1.image.ImageDeleteRequest
	(*ImageDeleteResponse)(nil),  // 12: content.v1.image.ImageDeleteResponse
	(*ImageShareRequest)(nil),    // 13: content.v1.image.ImageShareRequest
	(*ImageShareResponse)(nil),   // 14: content.v1.image.ImageShareResponse
	(*v1.FileMetadata)(nil),      // 15: common.v1.FileMetadata
}
var file_content_v1_image_image_proto_depIdxs = []int32{
	15, // 0: content.v1.image.ImageMetadata.file_metadata:type_name -> common.v1.FileMetadata
	3,  // 1: content.v1.image.ImageSearchRequest.query:type_name -> content.v1.image.ImageQuery
	0,  // 2: content.v1.image.ImageSearchResponse.images:type_name -> content.v1.image.ImageMetadata
	6,  // 3: content.v1.image.ImageUploadRequest.file_info:type_name -> content.v1.image.ImageFileInfo
	0,  // 4: content.v1.image.ImageUploadResponse.image:type_name -> content.v1.image.ImageMetadata
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_content_v1_image_image_proto_init() }
func file_content_v1_image_image_proto_init() {
	if File_content_v1_image_image_proto != nil {
		return
	}
	file_content_v1_image_image_proto_msgTypes[1].OneofWrappers = []any{}
	file_content_v1_image_image_proto_msgTypes[2].OneofWrappers = []any{}
	file_content_v1_image_image_proto_msgTypes[3].OneofWrappers = []any{}
	file_content_v1_image_image_proto_msgTypes[4].OneofWrappers = []any{}
	file_content_v1_image_image_proto_msgTypes[7].OneofWrappers = []any{}
	file_content_v1_image_image_proto_msgTypes[8].OneofWrappers = []any{
		(*ImageUploadRequest_FileInfo)(nil),
		(*ImageUploadRequest_ChunkData)(nil),
	}
	file_content_v1_image_image_proto_msgTypes[10].OneofWrappers = []any{}
	file_content_v1_image_image_proto_msgTypes[11].OneofWrappers = []any{}
	file_content_v1_image_image_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_v1_image_image_proto_rawDesc), len(file_content_v1_image_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_v1_image_image_proto_goTypes,
		DependencyIndexes: file_content_v1_image_image_proto_depIdxs,
		MessageInfos:      file_content_v1_image_image_proto_msgTypes,
	}.Build()
	File_content_v1_image_image_proto = out.File
	file_content_v1_image_image_proto_goTypes = nil
	file_content_v1_image_image_proto_depIdxs = nil
}
