// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: identity/auth.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityAuthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Site     string `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Otp      *int32 `protobuf:"varint,4,opt,name=otp,proto3,oneof" json:"otp,omitempty"`
}

func (x *IdentityAuthRequest) Reset() {
	*x = IdentityAuthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityAuthRequest) ProtoMessage() {}

func (x *IdentityAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityAuthRequest.ProtoReflect.Descriptor instead.
func (*IdentityAuthRequest) Descriptor() ([]byte, []int) {
	return file_identity_auth_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityAuthRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *IdentityAuthRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IdentityAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *IdentityAuthRequest) GetOtp() int32 {
	if x != nil && x.Otp != nil {
		return *x.Otp
	}
	return 0
}

type IdentityAuthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: `json:"accessToken,omitempty" bson:"accessToken,omitempty"`
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"accessToken,omitempty" bson:"accessToken,omitempty"`
	// @gotags: `json:"refreshToken,omitempty" bson:"refreshToken,omitempty"`
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken,omitempty" bson:"refreshToken,omitempty"`
	// @gotags: `json:"userDetails,omitempty" bson:"userDetails,omitempty"`
	UserDetails *structpb.Struct `protobuf:"bytes,3,opt,name=user_details,json=userDetails,proto3" json:"userDetails,omitempty" bson:"userDetails,omitempty"`
	User        *Identity        `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *IdentityAuthResponse) Reset() {
	*x = IdentityAuthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_identity_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityAuthResponse) ProtoMessage() {}

func (x *IdentityAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityAuthResponse.ProtoReflect.Descriptor instead.
func (*IdentityAuthResponse) Descriptor() ([]byte, []int) {
	return file_identity_auth_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *IdentityAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *IdentityAuthResponse) GetUserDetails() *structpb.Struct {
	if x != nil {
		return x.UserDetails
	}
	return nil
}

func (x *IdentityAuthResponse) GetUser() *Identity {
	if x != nil {
		return x.User
	}
	return nil
}

var File_identity_auth_proto protoreflect.FileDescriptor

var file_identity_auth_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x1a,
	0x17, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x13, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x15, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6f,
	0x74, 0x70, 0x22, 0xc2, 0x01, 0x0a, 0x14, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23,
	0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x3a, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x26, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x79, 0x75, 0x75, 0x53, 0x61, 0x78, 0x65, 0x6e, 0x61,
	0x2f, 0x6d, 0x79, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x3b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_identity_auth_proto_rawDescOnce sync.Once
	file_identity_auth_proto_rawDescData = file_identity_auth_proto_rawDesc
)

func file_identity_auth_proto_rawDescGZIP() []byte {
	file_identity_auth_proto_rawDescOnce.Do(func() {
		file_identity_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_identity_auth_proto_rawDescData)
	})
	return file_identity_auth_proto_rawDescData
}

var file_identity_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_auth_proto_goTypes = []any{
	(*IdentityAuthRequest)(nil),  // 0: identity.IdentityAuthRequest
	(*IdentityAuthResponse)(nil), // 1: identity.IdentityAuthResponse
	(*structpb.Struct)(nil),      // 2: google.protobuf.Struct
	(*Identity)(nil),             // 3: identity.Identity
}
var file_identity_auth_proto_depIdxs = []int32{
	2, // 0: identity.IdentityAuthResponse.user_details:type_name -> google.protobuf.Struct
	3, // 1: identity.IdentityAuthResponse.user:type_name -> identity.Identity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_identity_auth_proto_init() }
func file_identity_auth_proto_init() {
	if File_identity_auth_proto != nil {
		return
	}
	file_identity_identity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_identity_auth_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IdentityAuthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_identity_auth_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IdentityAuthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_identity_auth_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_identity_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_auth_proto_goTypes,
		DependencyIndexes: file_identity_auth_proto_depIdxs,
		MessageInfos:      file_identity_auth_proto_msgTypes,
	}.Build()
	File_identity_auth_proto = out.File
	file_identity_auth_proto_rawDesc = nil
	file_identity_auth_proto_goTypes = nil
	file_identity_auth_proto_depIdxs = nil
}
