// Code generated by MockGen. DO NOT EDIT.
// Source: protos-go/authorizer/v1/authorizerService_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=protos-go/authorizer/v1/authorizerService_grpc.pb.go -destination=protos-go/mocks/authorizer/v1/authorizerService_mock.go -package=authorizer_mock
//

// Package authorizer_mock is a generated GoMock package.
package authorizer_mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/AyuuSaxena/protos-go/authorizer/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAuthorizerServiceClient is a mock of AuthorizerServiceClient interface.
type MockAuthorizerServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerServiceClientMockRecorder
	isgomock struct{}
}

// MockAuthorizerServiceClientMockRecorder is the mock recorder for MockAuthorizerServiceClient.
type MockAuthorizerServiceClientMockRecorder struct {
	mock *MockAuthorizerServiceClient
}

// NewMockAuthorizerServiceClient creates a new mock instance.
func NewMockAuthorizerServiceClient(ctrl *gomock.Controller) *MockAuthorizerServiceClient {
	mock := &MockAuthorizerServiceClient{ctrl: ctrl}
	mock.recorder = &MockAuthorizerServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizerServiceClient) EXPECT() *MockAuthorizerServiceClientMockRecorder {
	return m.recorder
}

// CheckAccess mocks base method.
func (m *MockAuthorizerServiceClient) CheckAccess(ctx context.Context, in *v1.CheckAccessRequest, opts ...grpc.CallOption) (*v1.CheckAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckAccess", varargs...)
	ret0, _ := ret[0].(*v1.CheckAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccess indicates an expected call of CheckAccess.
func (mr *MockAuthorizerServiceClientMockRecorder) CheckAccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccess", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).CheckAccess), varargs...)
}

// CheckBulkAccess mocks base method.
func (m *MockAuthorizerServiceClient) CheckBulkAccess(ctx context.Context, in *v1.CheckBulkAccessRequest, opts ...grpc.CallOption) (*v1.CheckBulkAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckBulkAccess", varargs...)
	ret0, _ := ret[0].(*v1.CheckBulkAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBulkAccess indicates an expected call of CheckBulkAccess.
func (mr *MockAuthorizerServiceClientMockRecorder) CheckBulkAccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBulkAccess", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).CheckBulkAccess), varargs...)
}

// CreatePermission mocks base method.
func (m *MockAuthorizerServiceClient) CreatePermission(ctx context.Context, in *v1.CreatePermissionRequest, opts ...grpc.CallOption) (*v1.CreatePermissionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePermission", varargs...)
	ret0, _ := ret[0].(*v1.CreatePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockAuthorizerServiceClientMockRecorder) CreatePermission(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).CreatePermission), varargs...)
}

// CreateRole mocks base method.
func (m *MockAuthorizerServiceClient) CreateRole(ctx context.Context, in *v1.CreateRoleRequest, opts ...grpc.CallOption) (*v1.CreateRoleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateRole", varargs...)
	ret0, _ := ret[0].(*v1.CreateRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockAuthorizerServiceClientMockRecorder) CreateRole(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).CreateRole), varargs...)
}

// CreateService mocks base method.
func (m *MockAuthorizerServiceClient) CreateService(ctx context.Context, in *v1.CreateServiceRequest, opts ...grpc.CallOption) (*v1.CreateServiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateService", varargs...)
	ret0, _ := ret[0].(*v1.CreateServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockAuthorizerServiceClientMockRecorder) CreateService(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).CreateService), varargs...)
}

// DeletePermission mocks base method.
func (m *MockAuthorizerServiceClient) DeletePermission(ctx context.Context, in *v1.DeletePermissionRequest, opts ...grpc.CallOption) (*v1.DeletePermissionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePermission", varargs...)
	ret0, _ := ret[0].(*v1.DeletePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockAuthorizerServiceClientMockRecorder) DeletePermission(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).DeletePermission), varargs...)
}

// DeleteRole mocks base method.
func (m *MockAuthorizerServiceClient) DeleteRole(ctx context.Context, in *v1.DeleteRoleRequest, opts ...grpc.CallOption) (*v1.DeleteRoleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRole", varargs...)
	ret0, _ := ret[0].(*v1.DeleteRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAuthorizerServiceClientMockRecorder) DeleteRole(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).DeleteRole), varargs...)
}

// DeleteService mocks base method.
func (m *MockAuthorizerServiceClient) DeleteService(ctx context.Context, in *v1.DeleteServiceRequest, opts ...grpc.CallOption) (*v1.DeleteServiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteService", varargs...)
	ret0, _ := ret[0].(*v1.DeleteServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteService indicates an expected call of DeleteService.
func (mr *MockAuthorizerServiceClientMockRecorder) DeleteService(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteService", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).DeleteService), varargs...)
}

// GetPermission mocks base method.
func (m *MockAuthorizerServiceClient) GetPermission(ctx context.Context, in *v1.GetPermissionRequest, opts ...grpc.CallOption) (*v1.GetPermissionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPermission", varargs...)
	ret0, _ := ret[0].(*v1.GetPermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockAuthorizerServiceClientMockRecorder) GetPermission(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).GetPermission), varargs...)
}

// GetRole mocks base method.
func (m *MockAuthorizerServiceClient) GetRole(ctx context.Context, in *v1.GetRoleRequest, opts ...grpc.CallOption) (*v1.GetRoleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRole", varargs...)
	ret0, _ := ret[0].(*v1.GetRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockAuthorizerServiceClientMockRecorder) GetRole(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).GetRole), varargs...)
}

// GetService mocks base method.
func (m *MockAuthorizerServiceClient) GetService(ctx context.Context, in *v1.GetServiceRequest, opts ...grpc.CallOption) (*v1.GetServiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetService", varargs...)
	ret0, _ := ret[0].(*v1.GetServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockAuthorizerServiceClientMockRecorder) GetService(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).GetService), varargs...)
}

// GetUserAccess mocks base method.
func (m *MockAuthorizerServiceClient) GetUserAccess(ctx context.Context, in *v1.GetUserAccessRequest, opts ...grpc.CallOption) (*v1.UserAccess, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserAccess", varargs...)
	ret0, _ := ret[0].(*v1.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccess indicates an expected call of GetUserAccess.
func (mr *MockAuthorizerServiceClientMockRecorder) GetUserAccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccess", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).GetUserAccess), varargs...)
}

// GrantAccess mocks base method.
func (m *MockAuthorizerServiceClient) GrantAccess(ctx context.Context, in *v1.GrantAccessRequest, opts ...grpc.CallOption) (*v1.GrantAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GrantAccess", varargs...)
	ret0, _ := ret[0].(*v1.GrantAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantAccess indicates an expected call of GrantAccess.
func (mr *MockAuthorizerServiceClientMockRecorder) GrantAccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAccess", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).GrantAccess), varargs...)
}

// ListPermissions mocks base method.
func (m *MockAuthorizerServiceClient) ListPermissions(ctx context.Context, in *v1.ListPermissionsRequest, opts ...grpc.CallOption) (*v1.ListPermissionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPermissions", varargs...)
	ret0, _ := ret[0].(*v1.ListPermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockAuthorizerServiceClientMockRecorder) ListPermissions(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).ListPermissions), varargs...)
}

// ListRoles mocks base method.
func (m *MockAuthorizerServiceClient) ListRoles(ctx context.Context, in *v1.ListRolesRequest, opts ...grpc.CallOption) (*v1.ListRolesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRoles", varargs...)
	ret0, _ := ret[0].(*v1.ListRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockAuthorizerServiceClientMockRecorder) ListRoles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).ListRoles), varargs...)
}

// ListServices mocks base method.
func (m *MockAuthorizerServiceClient) ListServices(ctx context.Context, in *v1.ListServicesRequest, opts ...grpc.CallOption) (*v1.ListServicesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListServices", varargs...)
	ret0, _ := ret[0].(*v1.ListServicesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServices indicates an expected call of ListServices.
func (mr *MockAuthorizerServiceClientMockRecorder) ListServices(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).ListServices), varargs...)
}

// ListUserAccess mocks base method.
func (m *MockAuthorizerServiceClient) ListUserAccess(ctx context.Context, in *v1.ListUserAccessRequest, opts ...grpc.CallOption) (*v1.ListUserAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListUserAccess", varargs...)
	ret0, _ := ret[0].(*v1.ListUserAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserAccess indicates an expected call of ListUserAccess.
func (mr *MockAuthorizerServiceClientMockRecorder) ListUserAccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserAccess", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).ListUserAccess), varargs...)
}

// RevokeAccess mocks base method.
func (m *MockAuthorizerServiceClient) RevokeAccess(ctx context.Context, in *v1.RevokeAccessRequest, opts ...grpc.CallOption) (*v1.RevokeAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RevokeAccess", varargs...)
	ret0, _ := ret[0].(*v1.RevokeAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAccess indicates an expected call of RevokeAccess.
func (mr *MockAuthorizerServiceClientMockRecorder) RevokeAccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccess", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).RevokeAccess), varargs...)
}

// UpdatePermission mocks base method.
func (m *MockAuthorizerServiceClient) UpdatePermission(ctx context.Context, in *v1.UpdatePermissionRequest, opts ...grpc.CallOption) (*v1.UpdatePermissionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePermission", varargs...)
	ret0, _ := ret[0].(*v1.UpdatePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePermission indicates an expected call of UpdatePermission.
func (mr *MockAuthorizerServiceClientMockRecorder) UpdatePermission(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermission", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).UpdatePermission), varargs...)
}

// UpdateRole mocks base method.
func (m *MockAuthorizerServiceClient) UpdateRole(ctx context.Context, in *v1.UpdateRoleRequest, opts ...grpc.CallOption) (*v1.UpdateRoleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateRole", varargs...)
	ret0, _ := ret[0].(*v1.UpdateRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockAuthorizerServiceClientMockRecorder) UpdateRole(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).UpdateRole), varargs...)
}

// UpdateService mocks base method.
func (m *MockAuthorizerServiceClient) UpdateService(ctx context.Context, in *v1.UpdateServiceRequest, opts ...grpc.CallOption) (*v1.UpdateServiceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateService", varargs...)
	ret0, _ := ret[0].(*v1.UpdateServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockAuthorizerServiceClientMockRecorder) UpdateService(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockAuthorizerServiceClient)(nil).UpdateService), varargs...)
}

// MockAuthorizerServiceServer is a mock of AuthorizerServiceServer interface.
type MockAuthorizerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerServiceServerMockRecorder
	isgomock struct{}
}

// MockAuthorizerServiceServerMockRecorder is the mock recorder for MockAuthorizerServiceServer.
type MockAuthorizerServiceServerMockRecorder struct {
	mock *MockAuthorizerServiceServer
}

// NewMockAuthorizerServiceServer creates a new mock instance.
func NewMockAuthorizerServiceServer(ctrl *gomock.Controller) *MockAuthorizerServiceServer {
	mock := &MockAuthorizerServiceServer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizerServiceServer) EXPECT() *MockAuthorizerServiceServerMockRecorder {
	return m.recorder
}

// CheckAccess mocks base method.
func (m *MockAuthorizerServiceServer) CheckAccess(arg0 context.Context, arg1 *v1.CheckAccessRequest) (*v1.CheckAccessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccess", arg0, arg1)
	ret0, _ := ret[0].(*v1.CheckAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccess indicates an expected call of CheckAccess.
func (mr *MockAuthorizerServiceServerMockRecorder) CheckAccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccess", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).CheckAccess), arg0, arg1)
}

// CheckBulkAccess mocks base method.
func (m *MockAuthorizerServiceServer) CheckBulkAccess(arg0 context.Context, arg1 *v1.CheckBulkAccessRequest) (*v1.CheckBulkAccessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBulkAccess", arg0, arg1)
	ret0, _ := ret[0].(*v1.CheckBulkAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBulkAccess indicates an expected call of CheckBulkAccess.
func (mr *MockAuthorizerServiceServerMockRecorder) CheckBulkAccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBulkAccess", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).CheckBulkAccess), arg0, arg1)
}

// CreatePermission mocks base method.
func (m *MockAuthorizerServiceServer) CreatePermission(arg0 context.Context, arg1 *v1.CreatePermissionRequest) (*v1.CreatePermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermission", arg0, arg1)
	ret0, _ := ret[0].(*v1.CreatePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermission indicates an expected call of CreatePermission.
func (mr *MockAuthorizerServiceServerMockRecorder) CreatePermission(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermission", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).CreatePermission), arg0, arg1)
}

// CreateRole mocks base method.
func (m *MockAuthorizerServiceServer) CreateRole(arg0 context.Context, arg1 *v1.CreateRoleRequest) (*v1.CreateRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", arg0, arg1)
	ret0, _ := ret[0].(*v1.CreateRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockAuthorizerServiceServerMockRecorder) CreateRole(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).CreateRole), arg0, arg1)
}

// CreateService mocks base method.
func (m *MockAuthorizerServiceServer) CreateService(arg0 context.Context, arg1 *v1.CreateServiceRequest) (*v1.CreateServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", arg0, arg1)
	ret0, _ := ret[0].(*v1.CreateServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockAuthorizerServiceServerMockRecorder) CreateService(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).CreateService), arg0, arg1)
}

// DeletePermission mocks base method.
func (m *MockAuthorizerServiceServer) DeletePermission(arg0 context.Context, arg1 *v1.DeletePermissionRequest) (*v1.DeletePermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermission", arg0, arg1)
	ret0, _ := ret[0].(*v1.DeletePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePermission indicates an expected call of DeletePermission.
func (mr *MockAuthorizerServiceServerMockRecorder) DeletePermission(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermission", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).DeletePermission), arg0, arg1)
}

// DeleteRole mocks base method.
func (m *MockAuthorizerServiceServer) DeleteRole(arg0 context.Context, arg1 *v1.DeleteRoleRequest) (*v1.DeleteRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", arg0, arg1)
	ret0, _ := ret[0].(*v1.DeleteRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockAuthorizerServiceServerMockRecorder) DeleteRole(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).DeleteRole), arg0, arg1)
}

// DeleteService mocks base method.
func (m *MockAuthorizerServiceServer) DeleteService(arg0 context.Context, arg1 *v1.DeleteServiceRequest) (*v1.DeleteServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteService", arg0, arg1)
	ret0, _ := ret[0].(*v1.DeleteServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteService indicates an expected call of DeleteService.
func (mr *MockAuthorizerServiceServerMockRecorder) DeleteService(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteService", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).DeleteService), arg0, arg1)
}

// GetPermission mocks base method.
func (m *MockAuthorizerServiceServer) GetPermission(arg0 context.Context, arg1 *v1.GetPermissionRequest) (*v1.GetPermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermission", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetPermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockAuthorizerServiceServerMockRecorder) GetPermission(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).GetPermission), arg0, arg1)
}

// GetRole mocks base method.
func (m *MockAuthorizerServiceServer) GetRole(arg0 context.Context, arg1 *v1.GetRoleRequest) (*v1.GetRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockAuthorizerServiceServerMockRecorder) GetRole(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).GetRole), arg0, arg1)
}

// GetService mocks base method.
func (m *MockAuthorizerServiceServer) GetService(arg0 context.Context, arg1 *v1.GetServiceRequest) (*v1.GetServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockAuthorizerServiceServerMockRecorder) GetService(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).GetService), arg0, arg1)
}

// GetUserAccess mocks base method.
func (m *MockAuthorizerServiceServer) GetUserAccess(arg0 context.Context, arg1 *v1.GetUserAccessRequest) (*v1.UserAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccess", arg0, arg1)
	ret0, _ := ret[0].(*v1.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccess indicates an expected call of GetUserAccess.
func (mr *MockAuthorizerServiceServerMockRecorder) GetUserAccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccess", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).GetUserAccess), arg0, arg1)
}

// GrantAccess mocks base method.
func (m *MockAuthorizerServiceServer) GrantAccess(arg0 context.Context, arg1 *v1.GrantAccessRequest) (*v1.GrantAccessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantAccess", arg0, arg1)
	ret0, _ := ret[0].(*v1.GrantAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantAccess indicates an expected call of GrantAccess.
func (mr *MockAuthorizerServiceServerMockRecorder) GrantAccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAccess", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).GrantAccess), arg0, arg1)
}

// ListPermissions mocks base method.
func (m *MockAuthorizerServiceServer) ListPermissions(arg0 context.Context, arg1 *v1.ListPermissionsRequest) (*v1.ListPermissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions", arg0, arg1)
	ret0, _ := ret[0].(*v1.ListPermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockAuthorizerServiceServerMockRecorder) ListPermissions(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).ListPermissions), arg0, arg1)
}

// ListRoles mocks base method.
func (m *MockAuthorizerServiceServer) ListRoles(arg0 context.Context, arg1 *v1.ListRolesRequest) (*v1.ListRolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", arg0, arg1)
	ret0, _ := ret[0].(*v1.ListRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockAuthorizerServiceServerMockRecorder) ListRoles(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).ListRoles), arg0, arg1)
}

// ListServices mocks base method.
func (m *MockAuthorizerServiceServer) ListServices(arg0 context.Context, arg1 *v1.ListServicesRequest) (*v1.ListServicesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices", arg0, arg1)
	ret0, _ := ret[0].(*v1.ListServicesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServices indicates an expected call of ListServices.
func (mr *MockAuthorizerServiceServerMockRecorder) ListServices(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).ListServices), arg0, arg1)
}

// ListUserAccess mocks base method.
func (m *MockAuthorizerServiceServer) ListUserAccess(arg0 context.Context, arg1 *v1.ListUserAccessRequest) (*v1.ListUserAccessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserAccess", arg0, arg1)
	ret0, _ := ret[0].(*v1.ListUserAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserAccess indicates an expected call of ListUserAccess.
func (mr *MockAuthorizerServiceServerMockRecorder) ListUserAccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserAccess", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).ListUserAccess), arg0, arg1)
}

// RevokeAccess mocks base method.
func (m *MockAuthorizerServiceServer) RevokeAccess(arg0 context.Context, arg1 *v1.RevokeAccessRequest) (*v1.RevokeAccessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAccess", arg0, arg1)
	ret0, _ := ret[0].(*v1.RevokeAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAccess indicates an expected call of RevokeAccess.
func (mr *MockAuthorizerServiceServerMockRecorder) RevokeAccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccess", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).RevokeAccess), arg0, arg1)
}

// UpdatePermission mocks base method.
func (m *MockAuthorizerServiceServer) UpdatePermission(arg0 context.Context, arg1 *v1.UpdatePermissionRequest) (*v1.UpdatePermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermission", arg0, arg1)
	ret0, _ := ret[0].(*v1.UpdatePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePermission indicates an expected call of UpdatePermission.
func (mr *MockAuthorizerServiceServerMockRecorder) UpdatePermission(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermission", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).UpdatePermission), arg0, arg1)
}

// UpdateRole mocks base method.
func (m *MockAuthorizerServiceServer) UpdateRole(arg0 context.Context, arg1 *v1.UpdateRoleRequest) (*v1.UpdateRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", arg0, arg1)
	ret0, _ := ret[0].(*v1.UpdateRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockAuthorizerServiceServerMockRecorder) UpdateRole(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).UpdateRole), arg0, arg1)
}

// UpdateService mocks base method.
func (m *MockAuthorizerServiceServer) UpdateService(arg0 context.Context, arg1 *v1.UpdateServiceRequest) (*v1.UpdateServiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", arg0, arg1)
	ret0, _ := ret[0].(*v1.UpdateServiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockAuthorizerServiceServerMockRecorder) UpdateService(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).UpdateService), arg0, arg1)
}

// mustEmbedUnimplementedAuthorizerServiceServer mocks base method.
func (m *MockAuthorizerServiceServer) mustEmbedUnimplementedAuthorizerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthorizerServiceServer")
}

// mustEmbedUnimplementedAuthorizerServiceServer indicates an expected call of mustEmbedUnimplementedAuthorizerServiceServer.
func (mr *MockAuthorizerServiceServerMockRecorder) mustEmbedUnimplementedAuthorizerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthorizerServiceServer", reflect.TypeOf((*MockAuthorizerServiceServer)(nil).mustEmbedUnimplementedAuthorizerServiceServer))
}

// MockUnsafeAuthorizerServiceServer is a mock of UnsafeAuthorizerServiceServer interface.
type MockUnsafeAuthorizerServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeAuthorizerServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeAuthorizerServiceServerMockRecorder is the mock recorder for MockUnsafeAuthorizerServiceServer.
type MockUnsafeAuthorizerServiceServerMockRecorder struct {
	mock *MockUnsafeAuthorizerServiceServer
}

// NewMockUnsafeAuthorizerServiceServer creates a new mock instance.
func NewMockUnsafeAuthorizerServiceServer(ctrl *gomock.Controller) *MockUnsafeAuthorizerServiceServer {
	mock := &MockUnsafeAuthorizerServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeAuthorizerServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeAuthorizerServiceServer) EXPECT() *MockUnsafeAuthorizerServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedAuthorizerServiceServer mocks base method.
func (m *MockUnsafeAuthorizerServiceServer) mustEmbedUnimplementedAuthorizerServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedAuthorizerServiceServer")
}

// mustEmbedUnimplementedAuthorizerServiceServer indicates an expected call of mustEmbedUnimplementedAuthorizerServiceServer.
func (mr *MockUnsafeAuthorizerServiceServerMockRecorder) mustEmbedUnimplementedAuthorizerServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedAuthorizerServiceServer", reflect.TypeOf((*MockUnsafeAuthorizerServiceServer)(nil).mustEmbedUnimplementedAuthorizerServiceServer))
}
